// Generated by scripts/sync_l10n.py from spec/l10n/. Do not edit.
import Foundation

/// The sample's own copy, one accessor per key in `spec/l10n/app/en.json`.
public enum UseSmileIDSampleStrings {
  public static var commonCancel: String {
    text("common_cancel")
  }

  public static var commonContinue: String {
    text("common_continue")
  }

  public static var commonRetry: String {
    text("common_retry")
  }

  public static var commonTryAgain: String {
    text("common_try_again")
  }

  public static var commonDone: String {
    text("common_done")
  }

  public static var commonDelete: String {
    text("common_delete")
  }

  public static var commonHide: String {
    text("common_hide")
  }

  public static var commonBack: String {
    text("common_back")
  }

  public static var commonUndo: String {
    text("common_undo")
  }

  public static func commonCloseNamed(title: String) -> String {
    String(format: text("common_close_named"), title)
  }

  public static func commonCopyNamed(label: String) -> String {
    String(format: text("common_copy_named"), label)
  }

  public static func commonRequiredNamed(label: String) -> String {
    String(format: text("common_required_named"), label)
  }

  public static var commonSearch: String {
    text("common_search")
  }

  public static var navProducts: String {
    text("nav_products")
  }

  public static var navVerifications: String {
    text("nav_verifications")
  }

  public static var navSettings: String {
    text("nav_settings")
  }

  public static var navToken: String {
    text("nav_token")
  }

  public static var navTokenSession: String {
    text("nav_token_session")
  }

  public static var productsTitle: String {
    text("products_title")
  }

  public static var productsSubtitle: String {
    text("products_subtitle")
  }

  public static var productsSwitchProfile: String {
    text("products_switch_profile")
  }

  public static var productsSectionAuthentication: String {
    text("products_section_authentication")
  }

  public static var productsSectionOnboarding: String {
    text("products_section_onboarding")
  }

  public static var productSmartSelfieEnrollment: String {
    text("product_smart_selfie_enrollment")
  }

  public static var productSmartSelfieAuthentication: String {
    text("product_smart_selfie_authentication")
  }

  public static var productDocumentVerification: String {
    text("product_document_verification")
  }

  public static var productEnhancedDocumentVerification: String {
    text("product_enhanced_document_verification")
  }

  public static var productResidencyDocumentVerification: String {
    text("product_residency_document_verification")
  }

  public static var productBiometricKyc: String {
    text("product_biometric_kyc")
  }

  public static var productEnhancedKyc: String {
    text("product_enhanced_kyc")
  }

  public static var productCardRegistration: String {
    text("product_card_registration")
  }

  public static var productCardAuth: String {
    text("product_card_auth")
  }

  public static var productCardDocument: String {
    text("product_card_document")
  }

  public static var productCardEnhancedDoc: String {
    text("product_card_enhanced_doc")
  }

  public static var productCardResidencyDoc: String {
    text("product_card_residency_doc")
  }

  public static var productCardBiometric: String {
    text("product_card_biometric")
  }

  public static var productCardEnhanced: String {
    text("product_card_enhanced")
  }

  public static var productFamilyVerification: String {
    text("product_family_verification")
  }

  public static var productFamilyKyc: String {
    text("product_family_kyc")
  }

  public static var sessionActive: String {
    text("session_active")
  }

  public static func sessionLinkedTo(sessionId: String) -> String {
    String(format: text("session_linked_to"), sessionId)
  }

  public static var sessionEnded: String {
    text("session_ended")
  }

  public static var sessionRelink: String {
    text("session_relink")
  }

  public static var sessionScan: String {
    text("session_scan")
  }

  public static var scanTitle: String {
    text("scan_title")
  }

  public static var scanFlashOn: String {
    text("scan_flash_on")
  }

  public static var scanFlashOff: String {
    text("scan_flash_off")
  }

  public static var scanPoint: String {
    text("scan_point")
  }

  public static var scanLineUp: String {
    text("scan_line_up")
  }

  public static var scanPortalPrefix: String {
    text("scan_portal_prefix")
  }

  public static var scanPortalLink: String {
    text("scan_portal_link")
  }

  public static var scanPortalSuffix: String {
    text("scan_portal_suffix")
  }

  public static var scanManualEntry: String {
    text("scan_manual_entry")
  }

  public static var scanPaste: String {
    text("scan_paste")
  }

  public static var scanLinkToken: String {
    text("scan_link_token")
  }

  public static var scanSimulated: String {
    text("scan_simulated")
  }

  public static var scanSimulate: String {
    text("scan_simulate")
  }

  public static var scanBindsConsent: String {
    text("scan_binds_consent")
  }

  public static var scanBindsDetails: String {
    text("scan_binds_details")
  }

  public static var scanFound: String {
    text("scan_found")
  }

  public static var scanLinked: String {
    text("scan_linked")
  }

  public static var scanNotAToken: String {
    text("scan_not_a_token")
  }

  public static var scanReading: String {
    text("scan_reading")
  }

  public static func scanRemaining(handle: String, remaining: String) -> String {
    String(format: text("scan_remaining"), handle, remaining)
  }

  public static var scanClipboardEmpty: String {
    text("scan_clipboard_empty")
  }

  public static var scanReasonSessionEnded: String {
    text("scan_reason_session_ended")
  }

  public static var scanReasonNeeded: String {
    text("scan_reason_needed")
  }

  public static var scanSpanExpired: String {
    text("scan_span_expired")
  }

  public static var scanEnvironmentSandbox: String {
    text("scan_environment_sandbox")
  }

  public static var scanEnvironmentProduction: String {
    text("scan_environment_production")
  }

  public static var tokenErrorSegments: String {
    text("token_error_segments")
  }

  public static var tokenErrorPayloadEncoding: String {
    text("token_error_payload_encoding")
  }

  public static var tokenErrorPayloadJson: String {
    text("token_error_payload_json")
  }

  public static var tokenErrorIat: String {
    text("token_error_iat")
  }

  public static var tokenErrorExp: String {
    text("token_error_exp")
  }

  public static var tokenErrorExpOrder: String {
    text("token_error_exp_order")
  }

  public static var tokenErrorApiUrlMissing: String {
    text("token_error_api_url_missing")
  }

  public static func tokenErrorApiUrlUnknown(host: String) -> String {
    String(format: text("token_error_api_url_unknown"), host)
  }

  public static var tokenErrorApiUrlInvalid: String {
    text("token_error_api_url_invalid")
  }

  public static var tokenCallbackSet: String {
    text("token_callback_set")
  }

  public static var tokenCallbackDefault: String {
    text("token_callback_default")
  }

  public static func userDetailsSaveTo(profile: String) -> String {
    String(format: text("user_details_save_to"), profile)
  }

  public static var userDetailsSaveNew: String {
    text("user_details_save_new")
  }

  public static var userDetailsNoProfile: String {
    text("user_details_no_profile")
  }

  public static var userDetailsSwitchProfile: String {
    text("user_details_switch_profile")
  }

  public static var userDetailsSection: String {
    text("user_details_section")
  }

  public static var authUserIdEnter: String {
    text("auth_user_id_enter")
  }

  public static var authUserIdPlaceholder: String {
    text("auth_user_id_placeholder")
  }

  public static var authUserIdOr: String {
    text("auth_user_id_or")
  }

  public static var authUserIdPrevious: String {
    text("auth_user_id_previous")
  }

  public static var authUserIdPreviousBody: String {
    text("auth_user_id_previous_body")
  }

  public static var authUserIdEmptyTitle: String {
    text("auth_user_id_empty_title")
  }

  public static var authUserIdRun: String {
    text("auth_user_id_run")
  }

  public static var userDetailsProfileName: String {
    text("user_details_profile_name")
  }

  public static var userDetailsProfileNameHint: String {
    text("user_details_profile_name_hint")
  }

  public static var userDetailsFromToken: String {
    text("user_details_from_token")
  }

  public static var userDetailsEditHint: String {
    text("user_details_edit_hint")
  }

  public static var userFieldFirstName: String {
    text("user_field_first_name")
  }

  public static var userFieldLastName: String {
    text("user_field_last_name")
  }

  public static var userFieldEmail: String {
    text("user_field_email")
  }

  public static var userFieldPhone: String {
    text("user_field_phone")
  }

  public static var userFieldEmailOptional: String {
    text("user_field_email_optional")
  }

  public static var userFieldPhoneOptional: String {
    text("user_field_phone_optional")
  }

  public static var userFieldFirstNamePlaceholder: String {
    text("user_field_first_name_placeholder")
  }

  public static var userFieldLastNamePlaceholder: String {
    text("user_field_last_name_placeholder")
  }

  public static var userFieldEmailPlaceholder: String {
    text("user_field_email_placeholder")
  }

  public static var userFieldPhonePlaceholder: String {
    text("user_field_phone_placeholder")
  }

  public static var userFieldEmailError: String {
    text("user_field_email_error")
  }

  public static var userFieldPhoneError: String {
    text("user_field_phone_error")
  }

  public static var userRequirementFirstName: String {
    text("user_requirement_first_name")
  }

  public static var userRequirementLastName: String {
    text("user_requirement_last_name")
  }

  public static var userRequirementContact: String {
    text("user_requirement_contact")
  }

  public static func userRequirementOne(field: String) -> String {
    String(format: text("user_requirement_one"), field)
  }

  public static func userRequirementMany(fields: String) -> String {
    String(format: text("user_requirement_many"), fields)
  }

  public static var userRequirementSeparator: String {
    text("user_requirement_separator")
  }

  public static var kycCountry: String {
    text("kyc_country")
  }

  public static var kycIdType: String {
    text("kyc_id_type")
  }

  public static var kycIdNumber: String {
    text("kyc_id_number")
  }

  public static var kycDocument: String {
    text("kyc_document")
  }

  public static var kycCaptureAs: String {
    text("kyc_capture_as")
  }

  public static var kycSelectCountry: String {
    text("kyc_select_country")
  }

  public static var kycSelectIdType: String {
    text("kyc_select_id_type")
  }

  public static var kycLoadingIdTypes: String {
    text("kyc_loading_id_types")
  }

  public static var kycSelectDocument: String {
    text("kyc_select_document")
  }

  public static var kycLoadingDocuments: String {
    text("kyc_loading_documents")
  }

  public static var kycChooseCountryFirst: String {
    text("kyc_choose_country_first")
  }

  public static var kycChooseIdTypeFirst: String {
    text("kyc_choose_id_type_first")
  }

  public static func kycIdNumberPlaceholder(idType: String) -> String {
    String(format: text("kyc_id_number_placeholder"), idType)
  }

  public static func kycIdNumberExample(example: String) -> String {
    String(format: text("kyc_id_number_example"), example)
  }

  public static func kycIdNumberInvalidExample(idType: String, example: String) -> String {
    String(format: text("kyc_id_number_invalid_example"), idType, example)
  }

  public static func kycIdNumberInvalid(idType: String) -> String {
    String(format: text("kyc_id_number_invalid"), idType)
  }

  public static var catalogueAdviceUnauthorised: String {
    text("catalogue_advice_unauthorised")
  }

  public static var catalogueAdviceForbidden: String {
    text("catalogue_advice_forbidden")
  }

  public static var catalogueAdviceOffline: String {
    text("catalogue_advice_offline")
  }

  public static var pickerCountryTitle: String {
    text("picker_country_title")
  }

  public static var pickerCountrySearch: String {
    text("picker_country_search")
  }

  public static func pickerCountryNoMatch(query: String) -> String {
    String(format: text("picker_country_no_match"), query)
  }

  public static var pickerCountryEmpty: String {
    text("picker_country_empty")
  }

  public static var pickerCountryEmptyHint: String {
    text("picker_country_empty_hint")
  }

  public static var pickerIdTypeTitle: String {
    text("picker_id_type_title")
  }

  public static var pickerIdTypeSearch: String {
    text("picker_id_type_search")
  }

  public static func pickerIdTypeNoMatch(query: String) -> String {
    String(format: text("picker_id_type_no_match"), query)
  }

  public static func pickerIdTypeEmpty(country: String) -> String {
    String(format: text("picker_id_type_empty"), country)
  }

  public static var pickerDocumentTitle: String {
    text("picker_document_title")
  }

  public static var pickerDocumentSearch: String {
    text("picker_document_search")
  }

  public static func pickerDocumentNoMatch(query: String) -> String {
    String(format: text("picker_document_no_match"), query)
  }

  public static func pickerDocumentEmpty(country: String) -> String {
    String(format: text("picker_document_empty"), country)
  }

  public static var pickerChooseAnotherCountry: String {
    text("picker_choose_another_country")
  }

  public static var pickerThisCountry: String {
    text("picker_this_country")
  }

  public static var pickerCountryLoading: String {
    text("picker_country_loading")
  }

  public static var pickerCountryLoadFailed: String {
    text("picker_country_load_failed")
  }

  public static var pickerIdTypeLoading: String {
    text("picker_id_type_loading")
  }

  public static var pickerIdTypeLoadFailed: String {
    text("picker_id_type_load_failed")
  }

  public static var pickerDocumentLoading: String {
    text("picker_document_loading")
  }

  public static var pickerDocumentLoadFailed: String {
    text("picker_document_load_failed")
  }

  public static var captureAsTitle: String {
    text("capture_as_title")
  }

  public static var captureAsMatchDocument: String {
    text("capture_as_match_document")
  }

  public static var captureAsGreenBook: String {
    text("capture_as_green_book")
  }

  public static var captureAsPassport: String {
    text("capture_as_passport")
  }

  public static var captureAsGenericDocument: String {
    text("capture_as_generic_document")
  }

  public static var captureAsFrontAndBack: String {
    text("capture_as_front_and_back")
  }

  public static var captureAsFrontOnly: String {
    text("capture_as_front_only")
  }

  public static func captureAsMatches(captureAs: String) -> String {
    String(format: text("capture_as_matches"), captureAs)
  }

  public static func captureAsChosen(captureAs: String) -> String {
    String(format: text("capture_as_chosen"), captureAs)
  }

  public static func captureAsGenericSummary(captureAs: String, orientation: String, sides: String) -> String {
    String(format: text("capture_as_generic_summary"), captureAs, orientation, sides)
  }

  public static func captureAsGenericNamedSummary(name: String, orientation: String, sides: String) -> String {
    String(format: text("capture_as_generic_named_summary"), name, orientation, sides)
  }

  public static func captureAsMatchNamed(captureAs: String) -> String {
    String(format: text("capture_as_match_named"), captureAs)
  }

  public static var genericDocumentTitle: String {
    text("generic_document_title")
  }

  public static var genericDocumentDisplayName: String {
    text("generic_document_display_name")
  }

  public static var genericDocumentDefaultName: String {
    text("generic_document_default_name")
  }

  public static var genericDocumentBackSide: String {
    text("generic_document_back_side")
  }

  public static var genericDocumentBackSideHint: String {
    text("generic_document_back_side_hint")
  }

  public static var genericDocumentOrientation: String {
    text("generic_document_orientation")
  }

  public static var genericDocumentLandscape: String {
    text("generic_document_landscape")
  }

  public static var genericDocumentPortrait: String {
    text("generic_document_portrait")
  }

  public static var genericDocumentAspectRatio: String {
    text("generic_document_aspect_ratio")
  }

  public static var genericDocumentRatioOff: String {
    text("generic_document_ratio_off")
  }

  public static var genericDocumentRatioCard: String {
    text("generic_document_ratio_card")
  }

  public static var genericDocumentRatioPassport: String {
    text("generic_document_ratio_passport")
  }

  public static var genericDocumentRatioBooklet: String {
    text("generic_document_ratio_booklet")
  }

  public static var verificationsTitle: String {
    text("verifications_title")
  }

  public static var verificationsSelect: String {
    text("verifications_select")
  }

  public static var verificationsEmptyTitle: String {
    text("verifications_empty_title")
  }

  public static var verificationsEmptyBody: String {
    text("verifications_empty_body")
  }

  public static func verificationsFilteredEmptyTitle(filter: String) -> String {
    String(format: text("verifications_filtered_empty_title"), filter)
  }

  public static var verificationsFilteredEmptyBody: String {
    text("verifications_filtered_empty_body")
  }

  public static var verificationsFilterAll: String {
    text("verifications_filter_all")
  }

  public static var verificationsToday: String {
    text("verifications_today")
  }

  public static var verificationsYesterday: String {
    text("verifications_yesterday")
  }

  public static func verificationsSelected(count: Int) -> String {
    String(format: text("verifications_selected"), count)
  }

  public static var verificationsTapRows: String {
    text("verifications_tap_rows")
  }

  public static var verificationsTapHide: String {
    text("verifications_tap_hide")
  }

  public static var verificationsHideFromList: String {
    text("verifications_hide_from_list")
  }

  public static var verificationsHiddenOne: String {
    text("verifications_hidden_one")
  }

  public static func verificationsHiddenMany(count: Int) -> String {
    String(format: text("verifications_hidden_many"), count)
  }

  public static var statusClear: String {
    text("status_clear")
  }

  public static var statusAttention: String {
    text("status_attention")
  }

  public static var statusBlocked: String {
    text("status_blocked")
  }

  public static var statusError: String {
    text("status_error")
  }

  public static var statusProcessing: String {
    text("status_processing")
  }

  public static var jobResultApproved: String {
    text("job_result_approved")
  }

  public static var jobResultProvisional: String {
    text("job_result_provisional")
  }

  public static var jobResultRejected: String {
    text("job_result_rejected")
  }

  public static var jobResultSubmitted: String {
    text("job_result_submitted")
  }

  public static var jobErrorNotStored: String {
    text("job_error_not_stored")
  }

  public static var jobErrorUnreachable: String {
    text("job_error_unreachable")
  }

  public static func jobErrorUnexpected(type: String) -> String {
    String(format: text("job_error_unexpected"), type)
  }

  public static func statusRefreshResult(status: String, message: String) -> String {
    String(format: text("status_refresh_result"), status, message)
  }

  public static var statusRefreshProcessing: String {
    text("status_refresh_processing")
  }

  public static var statusRefreshNoSession: String {
    text("status_refresh_no_session")
  }

  public static var statusRefreshNotTokenJob: String {
    text("status_refresh_not_token_job")
  }

  public static var statusRefreshOtherPartner: String {
    text("status_refresh_other_partner")
  }

  public static func statusRefreshFailed(reason: String) -> String {
    String(format: text("status_refresh_failed"), reason)
  }

  public static var detailsTitle: String {
    text("details_title")
  }

  public static var detailsMissingTitle: String {
    text("details_missing_title")
  }

  public static func detailsMissingBody(jobId: String) -> String {
    String(format: text("details_missing_body"), jobId)
  }

  public static var detailsHide: String {
    text("details_hide")
  }

  public static var detailsSection: String {
    text("details_section")
  }

  public static var detailsJobId: String {
    text("details_job_id")
  }

  public static var detailsUserId: String {
    text("details_user_id")
  }

  public static var detailsMessage: String {
    text("details_message")
  }

  public static var detailsStatus: String {
    text("details_status")
  }

  public static func detailsCopied(label: String) -> String {
    String(format: text("details_copied"), label)
  }

  public static func detailsCopyFailed(label: String) -> String {
    String(format: text("details_copy_failed"), label)
  }

  public static var profilesTitle: String {
    text("profiles_title")
  }

  public static var profilesActiveSuffix: String {
    text("profiles_active_suffix")
  }

  public static var profilesCreate: String {
    text("profiles_create")
  }

  public static var profilesCreateHint: String {
    text("profiles_create_hint")
  }

  public static var profilesNoProfile: String {
    text("profiles_no_profile")
  }

  public static var profilesUnnamed: String {
    text("profiles_unnamed")
  }

  public static var profilesNoDetails: String {
    text("profiles_no_details")
  }

  public static func profilesCreated(profile: String) -> String {
    String(format: text("profiles_created"), profile)
  }

  public static var profilesMakeActive: String {
    text("profiles_make_active")
  }

  public static var profileConfigSectionProfile: String {
    text("profile_config_section_profile")
  }

  public static var profileConfigName: String {
    text("profile_config_name")
  }

  public static var profileConfigNameHint: String {
    text("profile_config_name_hint")
  }

  public static var profileConfigSectionDetails: String {
    text("profile_config_section_details")
  }

  public static var profileConfigSectionCallback: String {
    text("profile_config_section_callback")
  }

  public static var profileConfigCallbackLabel: String {
    text("profile_config_callback_label")
  }

  public static var profileConfigCallbackHint: String {
    text("profile_config_callback_hint")
  }

  public static var profileConfigDelete: String {
    text("profile_config_delete")
  }

  public static var profileConfigSave: String {
    text("profile_config_save")
  }

  public static var profileConfigUse: String {
    text("profile_config_use")
  }

  public static func profileConfigDeleteTitle(profile: String) -> String {
    String(format: text("profile_config_delete_title"), profile)
  }

  public static var profileConfigDeleteBody: String {
    text("profile_config_delete_body")
  }

  public static var profileSwitchTitle: String {
    text("profile_switch_title")
  }

  public static var profileSwitchNew: String {
    text("profile_switch_new")
  }

  public static var profileSwitchNewHint: String {
    text("profile_switch_new_hint")
  }

  public static var newProfileTitle: String {
    text("new_profile_title")
  }

  public static var newProfileName: String {
    text("new_profile_name")
  }

  public static var newProfileSectionDetails: String {
    text("new_profile_section_details")
  }

  public static var newProfileCreate: String {
    text("new_profile_create")
  }

  public static var settingsTitle: String {
    text("settings_title")
  }

  public static var settingsSectionProfile: String {
    text("settings_section_profile")
  }

  public static var settingsProfileConfigure: String {
    text("settings_profile_configure")
  }

  public static var settingsProfileCreate: String {
    text("settings_profile_create")
  }

  public static var settingsSectionCapture: String {
    text("settings_section_capture")
  }

  public static var settingsEnhancedSmartSelfie: String {
    text("settings_enhanced_smart_selfie")
  }

  public static var settingsEnhancedSmartSelfieBody: String {
    text("settings_enhanced_smart_selfie_body")
  }

  public static var settingsEnhancedSmartSelfieMutex: String {
    text("settings_enhanced_smart_selfie_mutex")
  }

  public static var settingsAgentMode: String {
    text("settings_agent_mode")
  }

  public static var settingsAgentModeBody: String {
    text("settings_agent_mode_body")
  }

  public static func settingsAgentModeMutex(setting: String) -> String {
    String(format: text("settings_agent_mode_mutex"), setting)
  }

  public static var settingsSectionAppearance: String {
    text("settings_section_appearance")
  }

  public static var settingsTheme: String {
    text("settings_theme")
  }

  public static var settingsSectionLanguage: String {
    text("settings_section_language")
  }

  public static var settingsLanguage: String {
    text("settings_language")
  }

  public static var settingsSectionSdkScreens: String {
    text("settings_section_sdk_screens")
  }

  public static var settingsConsent: String {
    text("settings_consent")
  }

  public static var settingsConsentBody: String {
    text("settings_consent_body")
  }

  public static var settingsConsentBound: String {
    text("settings_consent_bound")
  }

  public static var settingsInstructions: String {
    text("settings_instructions")
  }

  public static var settingsInstructionsBody: String {
    text("settings_instructions_body")
  }

  public static var settingsPreview: String {
    text("settings_preview")
  }

  public static var settingsPreviewBody: String {
    text("settings_preview_body")
  }

  public static var settingsSectionDocumentCapture: String {
    text("settings_section_document_capture")
  }

  public static var settingsCaptureMode: String {
    text("settings_capture_mode")
  }

  public static var settingsGalleryUpload: String {
    text("settings_gallery_upload")
  }

  public static var settingsGalleryUploadBody: String {
    text("settings_gallery_upload_body")
  }

  public static var settingsSkipBack: String {
    text("settings_skip_back")
  }

  public static var settingsSkipBackBody: String {
    text("settings_skip_back_body")
  }

  public static var settingsSelfieFirst: String {
    text("settings_selfie_first")
  }

  public static var settingsSelfieFirstBody: String {
    text("settings_selfie_first_body")
  }

  public static var settingsSectionAbout: String {
    text("settings_section_about")
  }

  public static var settingsDocumentation: String {
    text("settings_documentation")
  }

  public static var settingsSupport: String {
    text("settings_support")
  }

  public static var settingsSupportBody: String {
    text("settings_support_body")
  }

  public static var settingsSectionLegal: String {
    text("settings_section_legal")
  }

  public static var settingsTerms: String {
    text("settings_terms")
  }

  public static var settingsPrivacy: String {
    text("settings_privacy")
  }

  public static var settingsLicenses: String {
    text("settings_licenses")
  }

  public static var settingsSignOut: String {
    text("settings_sign_out")
  }

  public static var settingsSignOutTitle: String {
    text("settings_sign_out_title")
  }

  public static var settingsSignOutBody: String {
    text("settings_sign_out_body")
  }

  public static var flowInvalid: String {
    text("flow_invalid")
  }

  public static var captureModeTitle: String {
    text("capture_mode_title")
  }

  public static var captureModeAuto: String {
    text("capture_mode_auto")
  }

  public static var captureModeManual: String {
    text("capture_mode_manual")
  }

  public static var captureModeAutoWithFallback: String {
    text("capture_mode_auto_with_fallback")
  }

  public static var captureModeAutoBody: String {
    text("capture_mode_auto_body")
  }

  public static var captureModeManualBody: String {
    text("capture_mode_manual_body")
  }

  public static var captureModeAutoWithFallbackBody: String {
    text("capture_mode_auto_with_fallback_body")
  }

  public static var appearanceTitle: String {
    text("appearance_title")
  }

  public static var appearanceSystemLight: String {
    text("appearance_system_light")
  }

  public static var appearanceSystemDark: String {
    text("appearance_system_dark")
  }

  public static var appearanceLight: String {
    text("appearance_light")
  }

  public static var appearanceDark: String {
    text("appearance_dark")
  }

  public static var languageTitle: String {
    text("language_title")
  }

  public static func languageSystem(language: String) -> String {
    String(format: text("language_system"), language)
  }

  public static var languageAppliesOnRelaunch: String {
    text("language_applies_on_relaunch")
  }

  public static var licensesTitle: String {
    text("licenses_title")
  }

  public static var licensesEmptyTitle: String {
    text("licenses_empty_title")
  }

  public static var licensesEmptyBody: String {
    text("licenses_empty_body")
  }

  public static func licensesSection(count: Int) -> String {
    String(format: text("licenses_section"), count)
  }

  public static func licensesGoogleSection(count: Int) -> String {
    String(format: text("licenses_google_section"), count)
  }

  public static var licensesTextShipsWithComponent: String {
    text("licenses_text_ships_with_component")
  }

  public static func licensesTextShipsWithComponentAt(url: String) -> String {
    String(format: text("licenses_text_ships_with_component_at"), url)
  }

  public static func licensesOpen(license: String) -> String {
    String(format: text("licenses_open"), license)
  }

  /// Where the strings are read from; a right-to-left golden points it at one language's folder.
  nonisolated(unsafe) static var bundle: Bundle = .module

  private static func text(_ key: String) -> String {
    NSLocalizedString(key, bundle: bundle, comment: "")
  }
}
