// Generated by scripts/sync_l10n.py from spec/l10n/. Do not edit.
// One accessor per key, named after it, so a doc comment each would only repeat the name.
// ignore_for_file: public_member_api_docs

/// The sample's own copy, one accessor per key in `spec/l10n/app/en.json`.
final class UseSmileIDSampleStrings {
  const UseSmileIDSampleStrings._(this._values);

  /// The copy for [language], or English for a language the sample does not ship.
  factory UseSmileIDSampleStrings.forLanguage(String language) =>
      UseSmileIDSampleStrings._(_byLanguage[language] ?? _byLanguage['en']!);

  /// The language ids the sample ships, base language first.
  static const List<String> languages = ['en', 'fr', 'ar', 'he'];

  final Map<String, String> _values;

  String _format(String key, Map<String, Object> arguments) =>
      _values[key]!.replaceAllMapped(
        RegExp(r'\{(\w+)\}'),
        (match) => '${arguments[match.group(1)] ?? match.group(0)}',
      );

  String get commonCancel => _values['common_cancel']!;
  String get commonContinue => _values['common_continue']!;
  String get commonRetry => _values['common_retry']!;
  String get commonTryAgain => _values['common_try_again']!;
  String get commonDone => _values['common_done']!;
  String get commonDelete => _values['common_delete']!;
  String get commonHide => _values['common_hide']!;
  String get commonBack => _values['common_back']!;
  String get commonUndo => _values['common_undo']!;
  String commonCloseNamed({required String title}) =>
      _format('common_close_named', {'title': title});
  String commonCopyNamed({required String label}) =>
      _format('common_copy_named', {'label': label});
  String commonRequiredNamed({required String label}) =>
      _format('common_required_named', {'label': label});
  String get commonSearch => _values['common_search']!;
  String get navProducts => _values['nav_products']!;
  String get navVerifications => _values['nav_verifications']!;
  String get navSettings => _values['nav_settings']!;
  String get navToken => _values['nav_token']!;
  String get navTokenSession => _values['nav_token_session']!;
  String get productsTitle => _values['products_title']!;
  String get productsSubtitle => _values['products_subtitle']!;
  String get productsSwitchProfile => _values['products_switch_profile']!;
  String get productsSectionAuthentication =>
      _values['products_section_authentication']!;
  String get productsSectionOnboarding =>
      _values['products_section_onboarding']!;
  String get productSmartSelfieEnrollment =>
      _values['product_smart_selfie_enrollment']!;
  String get productSmartSelfieAuthentication =>
      _values['product_smart_selfie_authentication']!;
  String get productDocumentVerification =>
      _values['product_document_verification']!;
  String get productEnhancedDocumentVerification =>
      _values['product_enhanced_document_verification']!;
  String get productResidencyDocumentVerification =>
      _values['product_residency_document_verification']!;
  String get productBiometricKyc => _values['product_biometric_kyc']!;
  String get productEnhancedKyc => _values['product_enhanced_kyc']!;
  String get productCardRegistration => _values['product_card_registration']!;
  String get productCardAuth => _values['product_card_auth']!;
  String get productCardDocument => _values['product_card_document']!;
  String get productCardEnhancedDoc => _values['product_card_enhanced_doc']!;
  String get productCardResidencyDoc => _values['product_card_residency_doc']!;
  String get productCardBiometric => _values['product_card_biometric']!;
  String get productCardEnhanced => _values['product_card_enhanced']!;
  String get productFamilyVerification =>
      _values['product_family_verification']!;
  String get productFamilyKyc => _values['product_family_kyc']!;
  String get sessionActive => _values['session_active']!;
  String sessionLinkedTo({required String sessionId}) =>
      _format('session_linked_to', {'sessionId': sessionId});
  String get sessionEnded => _values['session_ended']!;
  String get sessionRelink => _values['session_relink']!;
  String get sessionScan => _values['session_scan']!;
  String get scanTitle => _values['scan_title']!;
  String get scanFlashOn => _values['scan_flash_on']!;
  String get scanFlashOff => _values['scan_flash_off']!;
  String get scanPoint => _values['scan_point']!;
  String get scanLineUp => _values['scan_line_up']!;
  String get scanPortalPrefix => _values['scan_portal_prefix']!;
  String get scanPortalLink => _values['scan_portal_link']!;
  String get scanPortalSuffix => _values['scan_portal_suffix']!;
  String get scanManualEntry => _values['scan_manual_entry']!;
  String get scanPaste => _values['scan_paste']!;
  String get scanLinkToken => _values['scan_link_token']!;
  String get scanSimulated => _values['scan_simulated']!;
  String get scanSimulate => _values['scan_simulate']!;
  String get scanBindsConsent => _values['scan_binds_consent']!;
  String get scanBindsDetails => _values['scan_binds_details']!;
  String get scanFound => _values['scan_found']!;
  String get scanLinked => _values['scan_linked']!;
  String get scanNotAToken => _values['scan_not_a_token']!;
  String get scanReading => _values['scan_reading']!;
  String scanRemaining({required String handle, required String remaining}) =>
      _format('scan_remaining', {'handle': handle, 'remaining': remaining});
  String get scanClipboardEmpty => _values['scan_clipboard_empty']!;
  String get scanReasonSessionEnded => _values['scan_reason_session_ended']!;
  String get scanReasonNeeded => _values['scan_reason_needed']!;
  String get scanSpanExpired => _values['scan_span_expired']!;
  String get scanEnvironmentSandbox => _values['scan_environment_sandbox']!;
  String get scanEnvironmentProduction =>
      _values['scan_environment_production']!;
  String get tokenErrorSegments => _values['token_error_segments']!;
  String get tokenErrorPayloadEncoding =>
      _values['token_error_payload_encoding']!;
  String get tokenErrorPayloadJson => _values['token_error_payload_json']!;
  String get tokenErrorIat => _values['token_error_iat']!;
  String get tokenErrorExp => _values['token_error_exp']!;
  String get tokenErrorExpOrder => _values['token_error_exp_order']!;
  String get tokenErrorApiUrlMissing => _values['token_error_api_url_missing']!;
  String tokenErrorApiUrlUnknown({required String host}) =>
      _format('token_error_api_url_unknown', {'host': host});
  String get tokenErrorApiUrlInvalid => _values['token_error_api_url_invalid']!;
  String get tokenCallbackSet => _values['token_callback_set']!;
  String get tokenCallbackDefault => _values['token_callback_default']!;
  String userDetailsSaveTo({required String profile}) =>
      _format('user_details_save_to', {'profile': profile});
  String get userDetailsSaveNew => _values['user_details_save_new']!;
  String get userDetailsNoProfile => _values['user_details_no_profile']!;
  String get userDetailsSwitchProfile =>
      _values['user_details_switch_profile']!;
  String get userDetailsSection => _values['user_details_section']!;
  String get userDetailsProfileName => _values['user_details_profile_name']!;
  String get userDetailsProfileNameHint =>
      _values['user_details_profile_name_hint']!;
  String get userDetailsFromToken => _values['user_details_from_token']!;
  String get userDetailsEditHint => _values['user_details_edit_hint']!;
  String get userFieldFirstName => _values['user_field_first_name']!;
  String get userFieldLastName => _values['user_field_last_name']!;
  String get userFieldEmail => _values['user_field_email']!;
  String get userFieldPhone => _values['user_field_phone']!;
  String get userFieldEmailOptional => _values['user_field_email_optional']!;
  String get userFieldPhoneOptional => _values['user_field_phone_optional']!;
  String get userFieldFirstNamePlaceholder =>
      _values['user_field_first_name_placeholder']!;
  String get userFieldLastNamePlaceholder =>
      _values['user_field_last_name_placeholder']!;
  String get userFieldEmailPlaceholder =>
      _values['user_field_email_placeholder']!;
  String get userFieldPhonePlaceholder =>
      _values['user_field_phone_placeholder']!;
  String get userFieldEmailError => _values['user_field_email_error']!;
  String get userFieldPhoneError => _values['user_field_phone_error']!;
  String get userRequirementFirstName =>
      _values['user_requirement_first_name']!;
  String get userRequirementLastName => _values['user_requirement_last_name']!;
  String get userRequirementContact => _values['user_requirement_contact']!;
  String userRequirementOne({required String field}) =>
      _format('user_requirement_one', {'field': field});
  String userRequirementMany({required String fields}) =>
      _format('user_requirement_many', {'fields': fields});
  String get userRequirementSeparator => _values['user_requirement_separator']!;
  String get kycCountry => _values['kyc_country']!;
  String get kycIdType => _values['kyc_id_type']!;
  String get kycIdNumber => _values['kyc_id_number']!;
  String get kycDocument => _values['kyc_document']!;
  String get kycCaptureAs => _values['kyc_capture_as']!;
  String get kycSelectCountry => _values['kyc_select_country']!;
  String get kycSelectIdType => _values['kyc_select_id_type']!;
  String get kycLoadingIdTypes => _values['kyc_loading_id_types']!;
  String get kycSelectDocument => _values['kyc_select_document']!;
  String get kycLoadingDocuments => _values['kyc_loading_documents']!;
  String get kycChooseCountryFirst => _values['kyc_choose_country_first']!;
  String get kycChooseIdTypeFirst => _values['kyc_choose_id_type_first']!;
  String kycIdNumberPlaceholder({required String idType}) =>
      _format('kyc_id_number_placeholder', {'idType': idType});
  String kycIdNumberExample({required String example}) =>
      _format('kyc_id_number_example', {'example': example});
  String kycIdNumberInvalidExample({
    required String idType,
    required String example,
  }) => _format('kyc_id_number_invalid_example', {
    'idType': idType,
    'example': example,
  });
  String kycIdNumberInvalid({required String idType}) =>
      _format('kyc_id_number_invalid', {'idType': idType});
  String get catalogueAdviceUnauthorised =>
      _values['catalogue_advice_unauthorised']!;
  String get catalogueAdviceForbidden => _values['catalogue_advice_forbidden']!;
  String get catalogueAdviceOffline => _values['catalogue_advice_offline']!;
  String get pickerCountryTitle => _values['picker_country_title']!;
  String get pickerCountrySearch => _values['picker_country_search']!;
  String pickerCountryNoMatch({required String query}) =>
      _format('picker_country_no_match', {'query': query});
  String get pickerCountryEmpty => _values['picker_country_empty']!;
  String get pickerCountryEmptyHint => _values['picker_country_empty_hint']!;
  String get pickerIdTypeTitle => _values['picker_id_type_title']!;
  String get pickerIdTypeSearch => _values['picker_id_type_search']!;
  String pickerIdTypeNoMatch({required String query}) =>
      _format('picker_id_type_no_match', {'query': query});
  String pickerIdTypeEmpty({required String country}) =>
      _format('picker_id_type_empty', {'country': country});
  String get pickerDocumentTitle => _values['picker_document_title']!;
  String get pickerDocumentSearch => _values['picker_document_search']!;
  String pickerDocumentNoMatch({required String query}) =>
      _format('picker_document_no_match', {'query': query});
  String pickerDocumentEmpty({required String country}) =>
      _format('picker_document_empty', {'country': country});
  String get pickerChooseAnotherCountry =>
      _values['picker_choose_another_country']!;
  String get pickerThisCountry => _values['picker_this_country']!;
  String get pickerCountryLoading => _values['picker_country_loading']!;
  String get pickerCountryLoadFailed => _values['picker_country_load_failed']!;
  String get pickerIdTypeLoading => _values['picker_id_type_loading']!;
  String get pickerIdTypeLoadFailed => _values['picker_id_type_load_failed']!;
  String get pickerDocumentLoading => _values['picker_document_loading']!;
  String get pickerDocumentLoadFailed =>
      _values['picker_document_load_failed']!;
  String get captureAsTitle => _values['capture_as_title']!;
  String get captureAsMatchDocument => _values['capture_as_match_document']!;
  String get captureAsGreenBook => _values['capture_as_green_book']!;
  String get captureAsPassport => _values['capture_as_passport']!;
  String get captureAsGenericDocument =>
      _values['capture_as_generic_document']!;
  String get captureAsFrontAndBack => _values['capture_as_front_and_back']!;
  String get captureAsFrontOnly => _values['capture_as_front_only']!;
  String captureAsMatches({required String captureAs}) =>
      _format('capture_as_matches', {'captureAs': captureAs});
  String captureAsChosen({required String captureAs}) =>
      _format('capture_as_chosen', {'captureAs': captureAs});
  String captureAsGenericSummary({
    required String captureAs,
    required String orientation,
    required String sides,
  }) => _format('capture_as_generic_summary', {
    'captureAs': captureAs,
    'orientation': orientation,
    'sides': sides,
  });
  String captureAsGenericNamedSummary({
    required String name,
    required String orientation,
    required String sides,
  }) => _format('capture_as_generic_named_summary', {
    'name': name,
    'orientation': orientation,
    'sides': sides,
  });
  String captureAsMatchNamed({required String captureAs}) =>
      _format('capture_as_match_named', {'captureAs': captureAs});
  String get genericDocumentTitle => _values['generic_document_title']!;
  String get genericDocumentDisplayName =>
      _values['generic_document_display_name']!;
  String get genericDocumentDefaultName =>
      _values['generic_document_default_name']!;
  String get genericDocumentBackSide => _values['generic_document_back_side']!;
  String get genericDocumentBackSideHint =>
      _values['generic_document_back_side_hint']!;
  String get genericDocumentOrientation =>
      _values['generic_document_orientation']!;
  String get genericDocumentLandscape => _values['generic_document_landscape']!;
  String get genericDocumentPortrait => _values['generic_document_portrait']!;
  String get genericDocumentAspectRatio =>
      _values['generic_document_aspect_ratio']!;
  String get genericDocumentRatioOff => _values['generic_document_ratio_off']!;
  String get genericDocumentRatioCard =>
      _values['generic_document_ratio_card']!;
  String get genericDocumentRatioPassport =>
      _values['generic_document_ratio_passport']!;
  String get genericDocumentRatioBooklet =>
      _values['generic_document_ratio_booklet']!;
  String get verificationsTitle => _values['verifications_title']!;
  String get verificationsSelect => _values['verifications_select']!;
  String get verificationsEmptyTitle => _values['verifications_empty_title']!;
  String get verificationsEmptyBody => _values['verifications_empty_body']!;
  String verificationsFilteredEmptyTitle({required String filter}) =>
      _format('verifications_filtered_empty_title', {'filter': filter});
  String get verificationsFilteredEmptyBody =>
      _values['verifications_filtered_empty_body']!;
  String get verificationsFilterAll => _values['verifications_filter_all']!;
  String get verificationsToday => _values['verifications_today']!;
  String get verificationsYesterday => _values['verifications_yesterday']!;
  String verificationsSelected({required int count}) =>
      _format('verifications_selected', {'count': count});
  String get verificationsTapRows => _values['verifications_tap_rows']!;
  String get verificationsTapHide => _values['verifications_tap_hide']!;
  String get verificationsHideFromList =>
      _values['verifications_hide_from_list']!;
  String get verificationsHiddenOne => _values['verifications_hidden_one']!;
  String verificationsHiddenMany({required int count}) =>
      _format('verifications_hidden_many', {'count': count});
  String get statusClear => _values['status_clear']!;
  String get statusAttention => _values['status_attention']!;
  String get statusBlocked => _values['status_blocked']!;
  String get statusProcessing => _values['status_processing']!;
  String get jobResultApproved => _values['job_result_approved']!;
  String get jobResultProvisional => _values['job_result_provisional']!;
  String get jobResultRejected => _values['job_result_rejected']!;
  String get jobResultSubmitted => _values['job_result_submitted']!;
  String get jobErrorNotStored => _values['job_error_not_stored']!;
  String get jobErrorUnreachable => _values['job_error_unreachable']!;
  String jobErrorUnexpected({required String type}) =>
      _format('job_error_unexpected', {'type': type});
  String statusRefreshResult({
    required String status,
    required String message,
  }) =>
      _format('status_refresh_result', {'status': status, 'message': message});
  String get statusRefreshProcessing => _values['status_refresh_processing']!;
  String get statusRefreshNoSession => _values['status_refresh_no_session']!;
  String get statusRefreshNotTokenJob =>
      _values['status_refresh_not_token_job']!;
  String get statusRefreshOtherPartner =>
      _values['status_refresh_other_partner']!;
  String statusRefreshFailed({required String reason}) =>
      _format('status_refresh_failed', {'reason': reason});
  String get detailsTitle => _values['details_title']!;
  String get detailsMissingTitle => _values['details_missing_title']!;
  String detailsMissingBody({required String jobId}) =>
      _format('details_missing_body', {'jobId': jobId});
  String get detailsHide => _values['details_hide']!;
  String get detailsSection => _values['details_section']!;
  String get detailsJobId => _values['details_job_id']!;
  String get detailsUserId => _values['details_user_id']!;
  String get detailsMessage => _values['details_message']!;
  String get detailsStatus => _values['details_status']!;
  String detailsCopied({required String label}) =>
      _format('details_copied', {'label': label});
  String detailsCopyFailed({required String label}) =>
      _format('details_copy_failed', {'label': label});
  String get profilesTitle => _values['profiles_title']!;
  String get profilesActiveSuffix => _values['profiles_active_suffix']!;
  String get profilesCreate => _values['profiles_create']!;
  String get profilesCreateHint => _values['profiles_create_hint']!;
  String get profilesNoProfile => _values['profiles_no_profile']!;
  String get profilesUnnamed => _values['profiles_unnamed']!;
  String get profilesNoDetails => _values['profiles_no_details']!;
  String profilesCreated({required String profile}) =>
      _format('profiles_created', {'profile': profile});
  String get profilesMakeActive => _values['profiles_make_active']!;
  String get profileConfigSectionProfile =>
      _values['profile_config_section_profile']!;
  String get profileConfigName => _values['profile_config_name']!;
  String get profileConfigNameHint => _values['profile_config_name_hint']!;
  String get profileConfigSectionDetails =>
      _values['profile_config_section_details']!;
  String get profileConfigSectionCallback =>
      _values['profile_config_section_callback']!;
  String get profileConfigCallbackLabel =>
      _values['profile_config_callback_label']!;
  String get profileConfigCallbackHint =>
      _values['profile_config_callback_hint']!;
  String get profileConfigDelete => _values['profile_config_delete']!;
  String get profileConfigSave => _values['profile_config_save']!;
  String get profileConfigUse => _values['profile_config_use']!;
  String profileConfigDeleteTitle({required String profile}) =>
      _format('profile_config_delete_title', {'profile': profile});
  String get profileConfigDeleteBody => _values['profile_config_delete_body']!;
  String get profileSwitchTitle => _values['profile_switch_title']!;
  String get profileSwitchNew => _values['profile_switch_new']!;
  String get profileSwitchNewHint => _values['profile_switch_new_hint']!;
  String get newProfileTitle => _values['new_profile_title']!;
  String get newProfileName => _values['new_profile_name']!;
  String get newProfileSectionDetails =>
      _values['new_profile_section_details']!;
  String get newProfileCreate => _values['new_profile_create']!;
  String get settingsTitle => _values['settings_title']!;
  String get settingsSectionProfile => _values['settings_section_profile']!;
  String get settingsProfileConfigure => _values['settings_profile_configure']!;
  String get settingsProfileCreate => _values['settings_profile_create']!;
  String get settingsSectionCapture => _values['settings_section_capture']!;
  String get settingsEnhancedSmartSelfie =>
      _values['settings_enhanced_smart_selfie']!;
  String get settingsEnhancedSmartSelfieBody =>
      _values['settings_enhanced_smart_selfie_body']!;
  String get settingsEnhancedSmartSelfieMutex =>
      _values['settings_enhanced_smart_selfie_mutex']!;
  String get settingsAgentMode => _values['settings_agent_mode']!;
  String get settingsAgentModeBody => _values['settings_agent_mode_body']!;
  String settingsAgentModeMutex({required String setting}) =>
      _format('settings_agent_mode_mutex', {'setting': setting});
  String get settingsSectionAppearance =>
      _values['settings_section_appearance']!;
  String get settingsTheme => _values['settings_theme']!;
  String get settingsSectionLanguage => _values['settings_section_language']!;
  String get settingsLanguage => _values['settings_language']!;
  String get settingsSectionSdkScreens =>
      _values['settings_section_sdk_screens']!;
  String get settingsConsent => _values['settings_consent']!;
  String get settingsConsentBody => _values['settings_consent_body']!;
  String get settingsConsentBound => _values['settings_consent_bound']!;
  String get settingsInstructions => _values['settings_instructions']!;
  String get settingsInstructionsBody => _values['settings_instructions_body']!;
  String get settingsPreview => _values['settings_preview']!;
  String get settingsPreviewBody => _values['settings_preview_body']!;
  String get settingsSectionDocumentCapture =>
      _values['settings_section_document_capture']!;
  String get settingsCaptureMode => _values['settings_capture_mode']!;
  String get settingsGalleryUpload => _values['settings_gallery_upload']!;
  String get settingsGalleryUploadBody =>
      _values['settings_gallery_upload_body']!;
  String get settingsSkipBack => _values['settings_skip_back']!;
  String get settingsSkipBackBody => _values['settings_skip_back_body']!;
  String get settingsSelfieFirst => _values['settings_selfie_first']!;
  String get settingsSelfieFirstBody => _values['settings_selfie_first_body']!;
  String get settingsSectionAbout => _values['settings_section_about']!;
  String get settingsDocumentation => _values['settings_documentation']!;
  String get settingsSupport => _values['settings_support']!;
  String get settingsSupportBody => _values['settings_support_body']!;
  String get settingsSectionLegal => _values['settings_section_legal']!;
  String get settingsTerms => _values['settings_terms']!;
  String get settingsPrivacy => _values['settings_privacy']!;
  String get settingsLicenses => _values['settings_licenses']!;
  String get settingsSignOut => _values['settings_sign_out']!;
  String get settingsSignOutTitle => _values['settings_sign_out_title']!;
  String get settingsSignOutBody => _values['settings_sign_out_body']!;
  String get flowInvalid => _values['flow_invalid']!;
  String get captureModeTitle => _values['capture_mode_title']!;
  String get captureModeAuto => _values['capture_mode_auto']!;
  String get captureModeManual => _values['capture_mode_manual']!;
  String get captureModeAutoWithFallback =>
      _values['capture_mode_auto_with_fallback']!;
  String get captureModeAutoBody => _values['capture_mode_auto_body']!;
  String get captureModeManualBody => _values['capture_mode_manual_body']!;
  String get captureModeAutoWithFallbackBody =>
      _values['capture_mode_auto_with_fallback_body']!;
  String get appearanceTitle => _values['appearance_title']!;
  String get appearanceSystemLight => _values['appearance_system_light']!;
  String get appearanceSystemDark => _values['appearance_system_dark']!;
  String get appearanceLight => _values['appearance_light']!;
  String get appearanceDark => _values['appearance_dark']!;
  String get languageTitle => _values['language_title']!;
  String languageSystem({required String language}) =>
      _format('language_system', {'language': language});
  String get languageAppliesOnRelaunch =>
      _values['language_applies_on_relaunch']!;
  String get licensesTitle => _values['licenses_title']!;
  String get licensesEmptyTitle => _values['licenses_empty_title']!;
  String get licensesEmptyBody => _values['licenses_empty_body']!;
  String licensesSection({required int count}) =>
      _format('licenses_section', {'count': count});
  String licensesGoogleSection({required int count}) =>
      _format('licenses_google_section', {'count': count});
  String get licensesTextShipsWithComponent =>
      _values['licenses_text_ships_with_component']!;
  String licensesTextShipsWithComponentAt({required String url}) =>
      _format('licenses_text_ships_with_component_at', {'url': url});
  String licensesOpen({required String license}) =>
      _format('licenses_open', {'license': license});

  static const Map<String, Map<String, String>> _byLanguage = {
    'en': {
      'common_cancel': 'Cancel',
      'common_continue': 'Continue',
      'common_retry': 'Retry',
      'common_try_again': 'Try again',
      'common_done': 'Done',
      'common_delete': 'Delete',
      'common_hide': 'Hide',
      'common_back': 'Back',
      'common_undo': 'Undo',
      'common_close_named': 'Close {title}',
      'common_copy_named': 'Copy {label}',
      'common_required_named': '{label} *',
      'common_search': 'Search',
      'nav_products': 'Products',
      'nav_verifications': 'Verifications',
      'nav_settings': 'Settings',
      'nav_token': 'Token',
      'nav_token_session': 'Token session',
      'products_title': 'Smile ID',
      'products_subtitle':
          'Try our suite of products powered by our Anti-Fraud SDKs',
      'products_switch_profile': 'Switch profile',
      'products_section_authentication': 'Authentication',
      'products_section_onboarding': 'Onboarding',
      'product_smart_selfie_enrollment': 'SmartSelfie Enrollment',
      'product_smart_selfie_authentication': 'SmartSelfie Authentication',
      'product_document_verification': 'Document Verification',
      'product_enhanced_document_verification':
          'Enhanced Document Verification',
      'product_residency_document_verification':
          'Residency Document Verification',
      'product_biometric_kyc': 'Biometric KYC',
      'product_enhanced_kyc': 'Enhanced KYC',
      'product_card_registration': 'Registration',
      'product_card_auth': 'Auth',
      'product_card_document': 'Document',
      'product_card_enhanced_doc': 'Enhanced Doc.',
      'product_card_residency_doc': 'Residency Doc.',
      'product_card_biometric': 'Biometric',
      'product_card_enhanced': 'Enhanced',
      'product_family_verification': 'Verification',
      'product_family_kyc': 'KYC',
      'session_active': 'ACTIVE TOKEN SESSION',
      'session_linked_to': 'Linked to session {sessionId}',
      'session_ended': 'TOKEN SESSION ENDED',
      'session_relink': 'Scan a token to relink',
      'session_scan': 'Scan',
      'scan_title': 'Scan token',
      'scan_flash_on': 'Turn flash on',
      'scan_flash_off': 'Turn flash off',
      'scan_point': 'Point at a Smile token QR',
      'scan_line_up':
          'Line up the code inside the frame to link this device to a verification session.',
      'scan_portal_prefix': 'Get a v3 token from the ',
      'scan_portal_link': 'Smile ID Portal',
      'scan_portal_suffix': ', under Security settings.',
      'scan_manual_entry': 'Or enter token manually',
      'scan_paste': 'Paste',
      'scan_link_token': 'Link token',
      'scan_simulated': 'SIMULATED SCAN',
      'scan_simulate': 'Simulate a successful scan',
      'scan_binds_consent': 'Binds consent',
      'scan_binds_details': 'Binds details',
      'scan_found': 'Token found',
      'scan_linked': 'Session linked',
      'scan_not_a_token': 'That is not a token',
      'scan_reading': 'Reading it now',
      'scan_remaining': '{handle} · {remaining} left',
      'scan_clipboard_empty': 'The clipboard holds no text to paste.',
      'scan_reason_session_ended':
          'Token session ended. Scan to continue where you left off.',
      'scan_reason_needed': 'Scan a token to start this verification.',
      'scan_span_expired': 'Expired',
      'scan_environment_sandbox': 'Sandbox',
      'scan_environment_production': 'Production',
      'token_error_segments':
          'A token is three dot-separated base64url segments; this is not.',
      'token_error_payload_encoding':
          'The token\'s payload segment is not base64url.',
      'token_error_payload_json':
          'The token\'s payload segment is not a JSON object.',
      'token_error_iat': 'The token carries no numeric iat claim.',
      'token_error_exp': 'The token carries no numeric exp claim.',
      'token_error_exp_order':
          'The token\'s exp claim is not after its iat claim.',
      'token_error_api_url_missing':
          'The token carries no api_url claim, so nothing says which environment it was minted for.',
      'token_error_api_url_unknown':
          'The token\'s api_url names {host}, which is not a Smile ID environment.',
      'token_error_api_url_invalid':
          'The token\'s api_url is not a URL, so it names no environment.',
      'token_callback_set': 'Set by the scanned token',
      'token_callback_default': 'The scanned token\'s partner default applies',
      'user_details_save_to': 'Save to {profile}',
      'user_details_save_new': 'Save as a new profile',
      'user_details_no_profile': 'Your details below will create one',
      'user_details_switch_profile': 'Tap to switch profile',
      'user_details_section': 'YOUR DETAILS',
      'user_details_profile_name': 'Profile name (optional)',
      'user_details_profile_name_hint': 'Shown on the consent screen',
      'user_details_from_token': 'Provided by token',
      'user_details_edit_hint': 'Tap any field to edit.',
      'user_field_first_name': 'First name',
      'user_field_last_name': 'Last name',
      'user_field_email': 'Email',
      'user_field_phone': 'Phone',
      'user_field_email_optional': 'Email (optional)',
      'user_field_phone_optional': 'Phone (optional)',
      'user_field_first_name_placeholder': 'Add first name',
      'user_field_last_name_placeholder': 'Add last name',
      'user_field_email_placeholder': 'name@company.com',
      'user_field_phone_placeholder': '+254 700 000 000',
      'user_field_email_error': 'Enter an email like name@company.com.',
      'user_field_phone_error':
          'Enter the number with its country code, like +254 700 000 000.',
      'user_requirement_first_name': 'first name',
      'user_requirement_last_name': 'last name',
      'user_requirement_contact': 'an email or phone number',
      'user_requirement_one': '{field} is required.',
      'user_requirement_many': 'Required: {fields}.',
      'user_requirement_separator': ', ',
      'kyc_country': 'COUNTRY',
      'kyc_id_type': 'ID TYPE',
      'kyc_id_number': 'ID NUMBER',
      'kyc_document': 'DOCUMENT',
      'kyc_capture_as': 'CAPTURE AS',
      'kyc_select_country': 'Select country',
      'kyc_select_id_type': 'Select ID type',
      'kyc_loading_id_types': 'Loading ID types…',
      'kyc_select_document': 'Select document',
      'kyc_loading_documents': 'Loading documents…',
      'kyc_choose_country_first': 'Choose a country first',
      'kyc_choose_id_type_first': 'Choose an ID type first',
      'kyc_id_number_placeholder': 'Enter your {idType}',
      'kyc_id_number_example': 'e.g. {example}',
      'kyc_id_number_invalid_example':
          'Doesn\'t match the {idType} format, e.g. {example}',
      'kyc_id_number_invalid': 'Doesn\'t match the {idType} format',
      'catalogue_advice_unauthorised':
          'The server refused this session\'s token. Link a new session, then try again',
      'catalogue_advice_forbidden':
          'Access denied: production may not be enabled for this partner, or this network is not allowed',
      'catalogue_advice_offline': 'Check your connection, then try again',
      'picker_country_title': 'Country',
      'picker_country_search': 'Search country',
      'picker_country_no_match': 'No country matches “{query}”',
      'picker_country_empty': 'No countries for this product',
      'picker_country_empty_hint': 'Try another product',
      'picker_id_type_title': 'ID type',
      'picker_id_type_search': 'Search ID type',
      'picker_id_type_no_match': 'No ID type matches “{query}”',
      'picker_id_type_empty': 'No ID types for {country}',
      'picker_document_title': 'Document',
      'picker_document_search': 'Search document',
      'picker_document_no_match': 'No document matches “{query}”',
      'picker_document_empty': 'No documents for {country}',
      'picker_choose_another_country': 'Choose another country',
      'picker_this_country': 'this country',
      'picker_country_loading': 'Loading countries',
      'picker_country_load_failed': 'Couldn\'t load countries',
      'picker_id_type_loading': 'Loading ID types',
      'picker_id_type_load_failed': 'Couldn\'t load ID types',
      'picker_document_loading': 'Loading documents',
      'picker_document_load_failed': 'Couldn\'t load documents',
      'capture_as_title': 'Capture as',
      'capture_as_match_document': 'Match document',
      'capture_as_green_book': 'Green Book preset',
      'capture_as_passport': 'Passport preset',
      'capture_as_generic_document': 'Generic document',
      'capture_as_front_and_back': 'front and back',
      'capture_as_front_only': 'front only',
      'capture_as_matches': '{captureAs} · matches document',
      'capture_as_chosen': '{captureAs} · chosen',
      'capture_as_generic_summary': '{captureAs} · {orientation} · {sides}',
      'capture_as_generic_named_summary':
          '{name} · {orientation} · {sides} · chosen',
      'capture_as_match_named': 'Match document ({captureAs})',
      'generic_document_title': 'Generic document',
      'generic_document_display_name': 'DISPLAY NAME',
      'generic_document_default_name': 'Document',
      'generic_document_back_side': 'Back side',
      'generic_document_back_side_hint': 'Capture the back after the front',
      'generic_document_orientation': 'ORIENTATION',
      'generic_document_landscape': 'Landscape',
      'generic_document_portrait': 'Portrait',
      'generic_document_aspect_ratio': 'ASPECT RATIO',
      'generic_document_ratio_off': 'Off',
      'generic_document_ratio_card': 'Card 1.586',
      'generic_document_ratio_passport': 'Passport 1.309',
      'generic_document_ratio_booklet': 'Booklet 0.748',
      'verifications_title': 'Verifications',
      'verifications_select': 'Select',
      'verifications_empty_title': 'No verifications yet',
      'verifications_empty_body':
          'Start a product above and the job lands here.',
      'verifications_filtered_empty_title': 'Nothing {filter}',
      'verifications_filtered_empty_body':
          'Other filters still have verifications.',
      'verifications_filter_all': 'All',
      'verifications_today': 'TODAY',
      'verifications_yesterday': 'YESTERDAY',
      'verifications_selected': '{count} selected',
      'verifications_tap_rows': 'Tap rows to select',
      'verifications_tap_hide': 'Tap “Hide from List” to confirm',
      'verifications_hide_from_list': 'Hide from List',
      'verifications_hidden_one': '1 verification hidden from App list',
      'verifications_hidden_many': '{count} verifications hidden from App list',
      'status_clear': 'Clear',
      'status_attention': 'Attention',
      'status_blocked': 'Blocked',
      'status_processing': 'Processing',
      'job_result_approved': 'Approved',
      'job_result_provisional': 'Provisional — needs review',
      'job_result_rejected': 'Rejected',
      'job_result_submitted': 'Submitted, awaiting result',
      'job_error_not_stored': 'The verification is no longer stored',
      'job_error_unreachable': 'Could not reach the server',
      'job_error_unexpected': 'Unexpected error: {type}',
      'status_refresh_result': '{status} — {message}',
      'status_refresh_processing': 'Still processing',
      'status_refresh_no_session': 'Scan a token first',
      'status_refresh_not_token_job': 'Not submitted under a scanned token',
      'status_refresh_other_partner': 'Submitted by a different partner',
      'status_refresh_failed': 'Could not check status: {reason}',
      'details_title': 'Verification details',
      'details_missing_title': 'No verification here',
      'details_missing_body': 'Nothing stored for jobId = {jobId}',
      'details_hide': 'Hide verification from the app list',
      'details_section': 'DETAILS',
      'details_job_id': 'Job ID',
      'details_user_id': 'User ID',
      'details_message': 'Message',
      'details_status': 'Status',
      'details_copied': '{label} copied',
      'details_copy_failed': '{label} could not be copied',
      'profiles_title': 'Profiles',
      'profiles_active_suffix': ' · active',
      'profiles_create': 'Create new profile',
      'profiles_create_hint': 'Its user details will live under it',
      'profiles_no_profile': 'No profile yet',
      'profiles_unnamed': 'Unnamed profile',
      'profiles_no_details': 'No user details yet',
      'profiles_created': '{profile} created',
      'profiles_make_active': 'Make active',
      'profile_config_section_profile': 'PROFILE',
      'profile_config_name': 'Profile name',
      'profile_config_name_hint': 'Shown on the consent screen',
      'profile_config_section_details': 'USER DETAILS — ATTACHED TO EVERY JOB',
      'profile_config_section_callback': 'CALLBACK URL',
      'profile_config_callback_label': 'Webhook URL',
      'profile_config_callback_hint': 'Uses your portal default',
      'profile_config_delete': 'Delete profile',
      'profile_config_save': 'Save changes',
      'profile_config_use': 'Use this profile',
      'profile_config_delete_title': 'Delete {profile}?',
      'profile_config_delete_body':
          'Its details and callback URL are removed from this device.',
      'profile_switch_title': 'Switch profile',
      'profile_switch_new': 'New profile',
      'profile_switch_new_hint': 'Run jobs as someone else',
      'new_profile_title': 'New profile',
      'new_profile_name': 'Profile name',
      'new_profile_section_details': 'USER DETAILS',
      'new_profile_create': 'Create profile',
      'settings_title': 'Settings',
      'settings_section_profile': 'PROFILE',
      'settings_profile_configure': 'Tap to configure',
      'settings_profile_create': 'Tap to create one',
      'settings_section_capture': 'CAPTURE',
      'settings_enhanced_smart_selfie': 'Enhanced SmartSelfie™',
      'settings_enhanced_smart_selfie_body': 'Face capture uses head-turns',
      'settings_enhanced_smart_selfie_mutex': 'Turns Agent mode off',
      'settings_agent_mode': 'Agent mode',
      'settings_agent_mode_body': 'Operator captures for the applicant',
      'settings_agent_mode_mutex': 'Turns {setting} off',
      'settings_section_appearance': 'APPEARANCE',
      'settings_theme': 'Theme',
      'settings_section_language': 'LANGUAGE',
      'settings_language': 'Language',
      'settings_section_sdk_screens': 'SDK SCREENS — SHOW OR SKIP FLOW STEPS',
      'settings_consent': 'Consent screen',
      'settings_consent_body': 'Ask permission before KYC checks',
      'settings_consent_bound':
          'The token grants consent, so the screen is skipped',
      'settings_instructions': 'Instruction screen',
      'settings_instructions_body': 'Prep tips before capture',
      'settings_preview': 'Preview screen',
      'settings_preview_body': 'Confirm or retake after capture',
      'settings_section_document_capture': 'DOCUMENT CAPTURE',
      'settings_capture_mode': 'Capture mode',
      'settings_gallery_upload': 'Gallery upload',
      'settings_gallery_upload_body': 'The system picker needs no permission',
      'settings_skip_back': 'Skip the back',
      'settings_skip_back_body': 'A Skip button on the back-side capture',
      'settings_selfie_first': 'Selfie first',
      'settings_selfie_first_body': 'The selfie before the document',
      'settings_section_about': 'ABOUT',
      'settings_documentation': 'Documentation',
      'settings_support': 'Support',
      'settings_support_body': 'Contact the Smile team',
      'settings_section_legal': 'LEGAL',
      'settings_terms': 'Terms of Service',
      'settings_privacy': 'Privacy Policy',
      'settings_licenses': 'Open-source licenses',
      'settings_sign_out': 'Sign out',
      'settings_sign_out_title': 'Sign out?',
      'settings_sign_out_body':
          'This ends the token session and deletes every profile on this device.',
      'flow_invalid': 'The flow did not validate',
      'capture_mode_title': 'Capture mode',
      'capture_mode_auto': 'Automatic',
      'capture_mode_manual': 'Manual',
      'capture_mode_auto_with_fallback': 'Automatic with manual fallback',
      'capture_mode_auto_body': 'Captures when the document is held steady',
      'capture_mode_manual_body': 'The shutter shows at once',
      'capture_mode_auto_with_fallback_body':
          'The shutter shows after 10 seconds',
      'appearance_title': 'Theme',
      'appearance_system_light': 'System (Light)',
      'appearance_system_dark': 'System (Dark)',
      'appearance_light': 'Light',
      'appearance_dark': 'Dark',
      'language_title': 'Language',
      'language_system': 'System ({language})',
      'language_applies_on_relaunch': 'Applies the next time the app opens.',
      'licenses_title': 'Open-source licenses',
      'licenses_empty_title': 'No notices bundled',
      'licenses_empty_body':
          'The generated licenses.json is missing from this build',
      'licenses_section': 'OPEN-SOURCE COMPONENTS — {count}',
      'licenses_google_section': 'UNDER GOOGLE\'S OWN TERMS — {count}',
      'licenses_text_ships_with_component':
          'The text ships with the component itself.',
      'licenses_text_ships_with_component_at':
          'The text ships with the component itself, at {url}',
      'licenses_open': 'Open {license}',
    },
    'fr': {
      'common_cancel': 'Annuler',
      'common_continue': 'Continuer',
      'common_retry': 'Réessayer',
      'common_try_again': 'Réessayer',
      'common_done': 'Terminé',
      'common_delete': 'Supprimer',
      'common_hide': 'Masquer',
      'common_back': 'Retour',
      'common_undo': 'Annuler',
      'common_close_named': 'Fermer {title}',
      'common_copy_named': 'Copier {label}',
      'common_required_named': '{label} *',
      'common_search': 'Rechercher',
      'nav_products': 'Produits',
      'nav_verifications': 'Vérifications',
      'nav_settings': 'Réglages',
      'nav_token': 'Jeton',
      'nav_token_session': 'Session de jeton',
      'products_title': 'Smile ID',
      'products_subtitle':
          'Essayez notre gamme de produits basés sur nos SDK anti-fraude',
      'products_switch_profile': 'Changer de profil',
      'products_section_authentication': 'Authentification',
      'products_section_onboarding': 'Intégration',
      'product_smart_selfie_enrollment': 'Inscription SmartSelfie',
      'product_smart_selfie_authentication': 'Authentification SmartSelfie',
      'product_document_verification': 'Vérification de document',
      'product_enhanced_document_verification':
          'Vérification de document renforcée',
      'product_residency_document_verification':
          'Vérification de titre de séjour',
      'product_biometric_kyc': 'KYC biométrique',
      'product_enhanced_kyc': 'KYC renforcé',
      'product_card_registration': 'Inscription',
      'product_card_auth': 'Authentification',
      'product_card_document': 'Document',
      'product_card_enhanced_doc': 'Document renforcé',
      'product_card_residency_doc': 'Titre de séjour',
      'product_card_biometric': 'Biométrique',
      'product_card_enhanced': 'Renforcé',
      'product_family_verification': 'Vérification',
      'product_family_kyc': 'KYC',
      'session_active': 'SESSION DE JETON ACTIVE',
      'session_linked_to': 'Liée à la session {sessionId}',
      'session_ended': 'SESSION DE JETON TERMINÉE',
      'session_relink': 'Scannez un jeton pour relier l’appareil',
      'session_scan': 'Scanner',
      'scan_title': 'Scanner un jeton',
      'scan_flash_on': 'Activer le flash',
      'scan_flash_off': 'Désactiver le flash',
      'scan_point': 'Visez un QR de jeton Smile',
      'scan_line_up':
          'Placez le code dans le cadre pour relier cet appareil à une session de vérification.',
      'scan_portal_prefix': 'Obtenez un jeton v3 depuis le ',
      'scan_portal_link': 'portail Smile ID',
      'scan_portal_suffix': ', dans les paramètres de sécurité.',
      'scan_manual_entry': 'Ou saisissez le jeton manuellement',
      'scan_paste': 'Coller',
      'scan_link_token': 'Relier le jeton',
      'scan_simulated': 'SCAN SIMULÉ',
      'scan_simulate': 'Simuler un scan réussi',
      'scan_binds_consent': 'Inclut le consentement',
      'scan_binds_details': 'Inclut les informations',
      'scan_found': 'Jeton trouvé',
      'scan_linked': 'Session reliée',
      'scan_not_a_token': 'Ce n’est pas un jeton',
      'scan_reading': 'Lecture en cours',
      'scan_remaining': '{handle} · {remaining} restantes',
      'scan_clipboard_empty':
          'Le presse-papiers ne contient aucun texte à coller.',
      'scan_reason_session_ended':
          'La session de jeton est terminée. Scannez pour reprendre là où vous vous étiez arrêté.',
      'scan_reason_needed':
          'Scannez un jeton pour commencer cette vérification.',
      'scan_span_expired': 'Expiré',
      'scan_environment_sandbox': 'Sandbox',
      'scan_environment_production': 'Production',
      'token_error_segments':
          'Un jeton comporte trois segments base64url séparés par des points ; ce n’est pas le cas ici.',
      'token_error_payload_encoding':
          'Le segment de charge utile du jeton n’est pas en base64url.',
      'token_error_payload_json':
          'Le segment de charge utile du jeton n’est pas un objet JSON.',
      'token_error_iat':
          'Le jeton ne contient pas de revendication iat numérique.',
      'token_error_exp':
          'Le jeton ne contient pas de revendication exp numérique.',
      'token_error_exp_order':
          'La revendication exp du jeton n’est pas postérieure à sa revendication iat.',
      'token_error_api_url_missing':
          'Le jeton ne contient pas de revendication api_url : rien n’indique pour quel environnement il a été émis.',
      'token_error_api_url_unknown':
          'L’api_url du jeton désigne {host}, qui n’est pas un environnement Smile ID.',
      'token_error_api_url_invalid':
          'L’api_url du jeton n’est pas une URL : elle ne désigne aucun environnement.',
      'token_callback_set': 'Défini par le jeton scanné',
      'token_callback_default':
          'La valeur par défaut du partenaire du jeton s’applique',
      'user_details_save_to': 'Enregistrer dans {profile}',
      'user_details_save_new': 'Enregistrer comme nouveau profil',
      'user_details_no_profile': 'Vos informations ci-dessous en créeront un',
      'user_details_switch_profile': 'Touchez pour changer de profil',
      'user_details_section': 'VOS INFORMATIONS',
      'user_details_profile_name': 'Nom du profil (facultatif)',
      'user_details_profile_name_hint': 'Affiché sur l’écran de consentement',
      'user_details_from_token': 'Fourni par le jeton',
      'user_details_edit_hint': 'Touchez un champ pour le modifier.',
      'user_field_first_name': 'Prénom',
      'user_field_last_name': 'Nom',
      'user_field_email': 'E-mail',
      'user_field_phone': 'Téléphone',
      'user_field_email_optional': 'E-mail (facultatif)',
      'user_field_phone_optional': 'Téléphone (facultatif)',
      'user_field_first_name_placeholder': 'Ajouter le prénom',
      'user_field_last_name_placeholder': 'Ajouter le nom',
      'user_field_email_placeholder': 'nom@entreprise.com',
      'user_field_phone_placeholder': '+254 700 000 000',
      'user_field_email_error':
          'Saisissez un e-mail du type nom@entreprise.com.',
      'user_field_phone_error':
          'Saisissez le numéro avec son indicatif, par exemple +254 700 000 000.',
      'user_requirement_first_name': 'le prénom',
      'user_requirement_last_name': 'le nom',
      'user_requirement_contact': 'un e-mail ou un numéro de téléphone',
      'user_requirement_one': 'Obligatoire : {field}.',
      'user_requirement_many': 'Obligatoire : {fields}.',
      'user_requirement_separator': ', ',
      'kyc_country': 'PAYS',
      'kyc_id_type': 'TYPE DE PIÈCE',
      'kyc_id_number': 'NUMÉRO DE PIÈCE',
      'kyc_document': 'DOCUMENT',
      'kyc_capture_as': 'CAPTURER COMME',
      'kyc_select_country': 'Choisir un pays',
      'kyc_select_id_type': 'Choisir un type de pièce',
      'kyc_loading_id_types': 'Chargement des types de pièce…',
      'kyc_select_document': 'Choisir un document',
      'kyc_loading_documents': 'Chargement des documents…',
      'kyc_choose_country_first': 'Choisissez d’abord un pays',
      'kyc_choose_id_type_first': 'Choisissez d’abord un type de pièce',
      'kyc_id_number_placeholder': 'Saisissez votre {idType}',
      'kyc_id_number_example': 'p. ex. {example}',
      'kyc_id_number_invalid_example':
          'Ne correspond pas au format {idType}, p. ex. {example}',
      'kyc_id_number_invalid': 'Ne correspond pas au format {idType}',
      'catalogue_advice_unauthorised':
          'Le serveur a refusé le jeton de cette session. Associez une nouvelle session, puis réessayez',
      'catalogue_advice_forbidden':
          'Accès refusé : la production n\'est peut-être pas activée pour ce partenaire, ou ce réseau n\'est pas autorisé',
      'catalogue_advice_offline': 'Vérifiez votre connexion, puis réessayez',
      'picker_country_title': 'Pays',
      'picker_country_search': 'Rechercher un pays',
      'picker_country_no_match': 'Aucun pays ne correspond à « {query} »',
      'picker_country_empty': 'Aucun pays pour ce produit',
      'picker_country_empty_hint': 'Essayez un autre produit',
      'picker_id_type_title': 'Type de pièce',
      'picker_id_type_search': 'Rechercher un type de pièce',
      'picker_id_type_no_match':
          'Aucun type de pièce ne correspond à « {query} »',
      'picker_id_type_empty': 'Aucun type de pièce pour {country}',
      'picker_document_title': 'Document',
      'picker_document_search': 'Rechercher un document',
      'picker_document_no_match': 'Aucun document ne correspond à « {query} »',
      'picker_document_empty': 'Aucun document pour {country}',
      'picker_choose_another_country': 'Choisissez un autre pays',
      'picker_this_country': 'ce pays',
      'picker_country_loading': 'Chargement des pays',
      'picker_country_load_failed': 'Impossible de charger les pays',
      'picker_id_type_loading': 'Chargement des types de pièce',
      'picker_id_type_load_failed': 'Impossible de charger les types de pièce',
      'picker_document_loading': 'Chargement des documents',
      'picker_document_load_failed': 'Impossible de charger les documents',
      'capture_as_title': 'Capturer comme',
      'capture_as_match_document': 'Selon le document',
      'capture_as_green_book': 'Préréglage Green Book',
      'capture_as_passport': 'Préréglage passeport',
      'capture_as_generic_document': 'Document générique',
      'capture_as_front_and_back': 'recto et verso',
      'capture_as_front_only': 'recto seul',
      'capture_as_matches': '{captureAs} · correspond au document',
      'capture_as_chosen': '{captureAs} · choisi',
      'capture_as_generic_summary': '{captureAs} · {orientation} · {sides}',
      'capture_as_generic_named_summary':
          '{name} · {orientation} · {sides} · choisi',
      'capture_as_match_named': 'Selon le document ({captureAs})',
      'generic_document_title': 'Document générique',
      'generic_document_display_name': 'NOM AFFICHÉ',
      'generic_document_default_name': 'Document',
      'generic_document_back_side': 'Verso',
      'generic_document_back_side_hint': 'Capturer le verso après le recto',
      'generic_document_orientation': 'ORIENTATION',
      'generic_document_landscape': 'Paysage',
      'generic_document_portrait': 'Portrait',
      'generic_document_aspect_ratio': 'FORMAT',
      'generic_document_ratio_off': 'Aucun',
      'generic_document_ratio_card': 'Carte 1,586',
      'generic_document_ratio_passport': 'Passeport 1,309',
      'generic_document_ratio_booklet': 'Livret 0,748',
      'verifications_title': 'Vérifications',
      'verifications_select': 'Sélectionner',
      'verifications_empty_title': 'Aucune vérification pour l’instant',
      'verifications_empty_body':
          'Lancez un produit ci-dessus et la tâche apparaîtra ici.',
      'verifications_filtered_empty_title': 'Aucune : {filter}',
      'verifications_filtered_empty_body':
          'D’autres filtres contiennent encore des vérifications.',
      'verifications_filter_all': 'Toutes',
      'verifications_today': 'AUJOURD’HUI',
      'verifications_yesterday': 'HIER',
      'verifications_selected': 'Sélection : {count}',
      'verifications_tap_rows': 'Touchez des lignes pour les sélectionner',
      'verifications_tap_hide':
          'Touchez « Masquer de la liste » pour confirmer',
      'verifications_hide_from_list': 'Masquer de la liste',
      'verifications_hidden_one':
          '1 vérification masquée de la liste de l\'app',
      'verifications_hidden_many':
          '{count} vérifications masquées de la liste de l\'app',
      'status_clear': 'Validée',
      'status_attention': 'À examiner',
      'status_blocked': 'Bloquée',
      'status_processing': 'En cours',
      'job_result_approved': 'Approuvée',
      'job_result_provisional': 'Provisoire — à examiner',
      'job_result_rejected': 'Rejetée',
      'job_result_submitted': 'Envoyée, résultat en attente',
      'job_error_not_stored': 'La vérification n’est plus enregistrée',
      'job_error_unreachable': 'Impossible de joindre le serveur',
      'job_error_unexpected': 'Erreur inattendue : {type}',
      'status_refresh_result': '{status} — {message}',
      'status_refresh_processing': 'Toujours en traitement',
      'status_refresh_no_session': 'Scannez d\'abord un jeton',
      'status_refresh_not_token_job': 'Non soumis avec un jeton scanné',
      'status_refresh_other_partner': 'Soumis par un autre partenaire',
      'status_refresh_failed': 'Impossible de vérifier le statut : {reason}',
      'details_title': 'Détails de la vérification',
      'details_missing_title': 'Aucune vérification ici',
      'details_missing_body': 'Rien d’enregistré pour jobId = {jobId}',
      'details_hide': 'Masquer la vérification de la liste',
      'details_section': 'DÉTAILS',
      'details_job_id': 'ID de tâche',
      'details_user_id': 'ID utilisateur',
      'details_message': 'Message',
      'details_status': 'Statut',
      'details_copied': '{label} copié',
      'details_copy_failed': 'Impossible de copier {label}',
      'profiles_title': 'Profils',
      'profiles_active_suffix': ' · actif',
      'profiles_create': 'Créer un profil',
      'profiles_create_hint':
          'Ses informations utilisateur y seront rattachées',
      'profiles_no_profile': 'Aucun profil',
      'profiles_unnamed': 'Profil sans nom',
      'profiles_no_details': 'Aucune information utilisateur',
      'profiles_created': '{profile} créé',
      'profiles_make_active': 'Activer',
      'profile_config_section_profile': 'PROFIL',
      'profile_config_name': 'Nom du profil',
      'profile_config_name_hint': 'Affiché sur l’écran de consentement',
      'profile_config_section_details':
          'INFORMATIONS UTILISATEUR — JOINTES À CHAQUE TÂCHE',
      'profile_config_section_callback': 'URL DE RAPPEL',
      'profile_config_callback_label': 'URL du webhook',
      'profile_config_callback_hint':
          'Utilise la valeur par défaut de votre portail',
      'profile_config_delete': 'Supprimer le profil',
      'profile_config_save': 'Enregistrer',
      'profile_config_use': 'Utiliser ce profil',
      'profile_config_delete_title': 'Supprimer {profile} ?',
      'profile_config_delete_body':
          'Ses informations et son URL de rappel seront supprimées de cet appareil.',
      'profile_switch_title': 'Changer de profil',
      'profile_switch_new': 'Nouveau profil',
      'profile_switch_new_hint':
          'Lancer des tâches au nom de quelqu’un d’autre',
      'new_profile_title': 'Nouveau profil',
      'new_profile_name': 'Nom du profil',
      'new_profile_section_details': 'INFORMATIONS UTILISATEUR',
      'new_profile_create': 'Créer le profil',
      'settings_title': 'Réglages',
      'settings_section_profile': 'PROFIL',
      'settings_profile_configure': 'Touchez pour configurer',
      'settings_profile_create': 'Touchez pour en créer un',
      'settings_section_capture': 'CAPTURE',
      'settings_enhanced_smart_selfie': 'Enhanced SmartSelfie™',
      'settings_enhanced_smart_selfie_body':
          'La capture du visage utilise des mouvements de tête',
      'settings_enhanced_smart_selfie_mutex': 'Désactive le mode agent',
      'settings_agent_mode': 'Mode agent',
      'settings_agent_mode_body': 'Un opérateur capture pour le demandeur',
      'settings_agent_mode_mutex': 'Désactive {setting}',
      'settings_section_appearance': 'APPARENCE',
      'settings_theme': 'Thème',
      'settings_section_language': 'LANGUE',
      'settings_language': 'Langue',
      'settings_section_sdk_screens':
          'ÉCRANS DU SDK — AFFICHER OU IGNORER DES ÉTAPES',
      'settings_consent': 'Écran de consentement',
      'settings_consent_body':
          'Demander l’autorisation avant les vérifications KYC',
      'settings_consent_bound':
          'Le jeton accorde le consentement : l’écran est ignoré',
      'settings_instructions': 'Écran d’instructions',
      'settings_instructions_body': 'Conseils avant la capture',
      'settings_preview': 'Écran d’aperçu',
      'settings_preview_body': 'Confirmer ou reprendre après la capture',
      'settings_section_document_capture': 'CAPTURE DE DOCUMENT',
      'settings_capture_mode': 'Mode de capture',
      'settings_gallery_upload': 'Import depuis la galerie',
      'settings_gallery_upload_body':
          'Le sélecteur du système ne demande aucune autorisation',
      'settings_skip_back': 'Ignorer le verso',
      'settings_skip_back_body':
          'Un bouton Ignorer lors de la capture du verso',
      'settings_selfie_first': 'Selfie d’abord',
      'settings_selfie_first_body': 'Le selfie avant le document',
      'settings_section_about': 'À PROPOS',
      'settings_documentation': 'Documentation',
      'settings_support': 'Assistance',
      'settings_support_body': 'Contacter l’équipe Smile',
      'settings_section_legal': 'MENTIONS LÉGALES',
      'settings_terms': 'Conditions d’utilisation',
      'settings_privacy': 'Politique de confidentialité',
      'settings_licenses': 'Licences open source',
      'settings_sign_out': 'Se déconnecter',
      'settings_sign_out_title': 'Se déconnecter ?',
      'settings_sign_out_body':
          'La session de jeton prend fin et tous les profils de cet appareil sont supprimés.',
      'flow_invalid': 'Le parcours n\'a pas été validé',
      'capture_mode_title': 'Mode de capture',
      'capture_mode_auto': 'Automatique',
      'capture_mode_manual': 'Manuel',
      'capture_mode_auto_with_fallback': 'Automatique avec repli manuel',
      'capture_mode_auto_body': 'Capture dès que le document est stable',
      'capture_mode_manual_body': 'Le déclencheur s\'affiche immédiatement',
      'capture_mode_auto_with_fallback_body':
          'Le déclencheur s\'affiche après 10 secondes',
      'appearance_title': 'Thème',
      'appearance_system_light': 'Système (clair)',
      'appearance_system_dark': 'Système (sombre)',
      'appearance_light': 'Clair',
      'appearance_dark': 'Sombre',
      'language_title': 'Langue',
      'language_system': 'Système ({language})',
      'language_applies_on_relaunch':
          'S’applique à la prochaine ouverture de l’app.',
      'licenses_title': 'Licences open source',
      'licenses_empty_title': 'Aucune mention incluse',
      'licenses_empty_body':
          'Le fichier licenses.json généré est absent de cette version',
      'licenses_section': 'COMPOSANTS OPEN SOURCE — {count}',
      'licenses_google_section':
          'SOUS LES CONDITIONS PROPRES À GOOGLE — {count}',
      'licenses_text_ships_with_component':
          'Le texte est fourni avec le composant.',
      'licenses_text_ships_with_component_at':
          'Le texte est fourni avec le composant lui-même, à l\'adresse {url}',
      'licenses_open': 'Ouvrir {license}',
    },
    'ar': {
      'common_cancel': 'إلغاء',
      'common_continue': 'متابعة',
      'common_retry': 'إعادة المحاولة',
      'common_try_again': 'حاول مرة أخرى',
      'common_done': 'تم',
      'common_delete': 'حذف',
      'common_hide': 'إخفاء',
      'common_back': 'رجوع',
      'common_undo': 'تراجع',
      'common_close_named': 'إغلاق {title}',
      'common_copy_named': 'نسخ {label}',
      'common_required_named': '{label} *',
      'common_search': 'بحث',
      'nav_products': 'المنتجات',
      'nav_verifications': 'عمليات التحقق',
      'nav_settings': 'الإعدادات',
      'nav_token': 'الرمز',
      'nav_token_session': 'جلسة الرمز',
      'products_title': 'Smile ID',
      'products_subtitle':
          'جرّب مجموعة منتجاتنا المبنية على حزم SDK لمكافحة الاحتيال',
      'products_switch_profile': 'تبديل الملف الشخصي',
      'products_section_authentication': 'المصادقة',
      'products_section_onboarding': 'التسجيل',
      'product_smart_selfie_enrollment': 'تسجيل SmartSelfie',
      'product_smart_selfie_authentication': 'مصادقة SmartSelfie',
      'product_document_verification': 'التحقق من المستند',
      'product_enhanced_document_verification': 'التحقق المعزّز من المستند',
      'product_residency_document_verification': 'التحقق من مستند الإقامة',
      'product_biometric_kyc': 'KYC بالقياسات الحيوية',
      'product_enhanced_kyc': 'KYC المعزّز',
      'product_card_registration': 'التسجيل',
      'product_card_auth': 'المصادقة',
      'product_card_document': 'المستند',
      'product_card_enhanced_doc': 'مستند معزّز',
      'product_card_residency_doc': 'مستند الإقامة',
      'product_card_biometric': 'القياسات الحيوية',
      'product_card_enhanced': 'معزّز',
      'product_family_verification': 'التحقق',
      'product_family_kyc': 'KYC',
      'session_active': 'جلسة رمز نشطة',
      'session_linked_to': 'مرتبطة بالجلسة {sessionId}',
      'session_ended': 'انتهت جلسة الرمز',
      'session_relink': 'امسح رمزًا لإعادة الربط',
      'session_scan': 'مسح',
      'scan_title': 'مسح الرمز',
      'scan_flash_on': 'تشغيل الفلاش',
      'scan_flash_off': 'إيقاف الفلاش',
      'scan_point': 'وجّه الكاميرا إلى رمز QR من Smile',
      'scan_line_up': 'ضع الرمز داخل الإطار لربط هذا الجهاز بجلسة تحقق.',
      'scan_portal_prefix': 'احصل على رمز v3 من ',
      'scan_portal_link': 'بوابة Smile ID',
      'scan_portal_suffix': '، ضمن إعدادات الأمان.',
      'scan_manual_entry': 'أو أدخل الرمز يدويًا',
      'scan_paste': 'لصق',
      'scan_link_token': 'ربط الرمز',
      'scan_simulated': 'مسح تجريبي',
      'scan_simulate': 'محاكاة مسح ناجح',
      'scan_binds_consent': 'يتضمن الموافقة',
      'scan_binds_details': 'يتضمن البيانات',
      'scan_found': 'تم العثور على الرمز',
      'scan_linked': 'تم ربط الجلسة',
      'scan_not_a_token': 'هذا ليس رمزًا',
      'scan_reading': 'جارٍ قراءته الآن',
      'scan_remaining': '{handle} · متبقٍ {remaining}',
      'scan_clipboard_empty': 'لا تحتوي الحافظة على نص للصق.',
      'scan_reason_session_ended':
          'انتهت جلسة الرمز. امسح رمزًا للمتابعة من حيث توقفت.',
      'scan_reason_needed': 'امسح رمزًا لبدء عملية التحقق هذه.',
      'scan_span_expired': 'منتهي الصلاحية',
      'scan_environment_sandbox': 'بيئة الاختبار',
      'scan_environment_production': 'بيئة الإنتاج',
      'token_error_segments':
          'يتكوّن الرمز من ثلاثة مقاطع base64url تفصل بينها نقاط، وهذا ليس كذلك.',
      'token_error_payload_encoding':
          'مقطع الحمولة في الرمز ليس بترميز base64url.',
      'token_error_payload_json': 'مقطع الحمولة في الرمز ليس كائن JSON.',
      'token_error_iat': 'لا يحتوي الرمز على مطالبة iat رقمية.',
      'token_error_exp': 'لا يحتوي الرمز على مطالبة exp رقمية.',
      'token_error_exp_order': 'مطالبة exp في الرمز ليست بعد مطالبة iat.',
      'token_error_api_url_missing':
          'لا يحتوي الرمز على مطالبة api_url، لذا لا شيء يحدد البيئة التي صدر لها.',
      'token_error_api_url_unknown':
          'يشير api_url في الرمز إلى {host}، وهي ليست بيئة من بيئات Smile ID.',
      'token_error_api_url_invalid':
          'قيمة api_url في الرمز ليست عنوان URL، لذا لا تحدد أي بيئة.',
      'token_callback_set': 'محدّد من الرمز الممسوح',
      'token_callback_default':
          'تُطبَّق القيمة الافتراضية للشريك في الرمز الممسوح',
      'user_details_save_to': 'حفظ في {profile}',
      'user_details_save_new': 'حفظ كملف شخصي جديد',
      'user_details_no_profile': 'ستُنشئ بياناتك أدناه ملفًا شخصيًا',
      'user_details_switch_profile': 'انقر لتبديل الملف الشخصي',
      'user_details_section': 'بياناتك',
      'user_details_profile_name': 'اسم الملف الشخصي (اختياري)',
      'user_details_profile_name_hint': 'يظهر في شاشة الموافقة',
      'user_details_from_token': 'مقدَّم من الرمز',
      'user_details_edit_hint': 'انقر على أي حقل لتعديله.',
      'user_field_first_name': 'الاسم الأول',
      'user_field_last_name': 'اسم العائلة',
      'user_field_email': 'البريد الإلكتروني',
      'user_field_phone': 'الهاتف',
      'user_field_email_optional': 'البريد الإلكتروني (اختياري)',
      'user_field_phone_optional': 'الهاتف (اختياري)',
      'user_field_first_name_placeholder': 'أضف الاسم الأول',
      'user_field_last_name_placeholder': 'أضف اسم العائلة',
      'user_field_email_placeholder': 'name@company.com',
      'user_field_phone_placeholder': '+254 700 000 000',
      'user_field_email_error': 'أدخل بريدًا إلكترونيًا مثل name@company.com.',
      'user_field_phone_error':
          'أدخل الرقم مع رمز البلد، مثل ‎+254 700 000 000.',
      'user_requirement_first_name': 'الاسم الأول',
      'user_requirement_last_name': 'اسم العائلة',
      'user_requirement_contact': 'بريد إلكتروني أو رقم هاتف',
      'user_requirement_one': 'مطلوب: {field}.',
      'user_requirement_many': 'مطلوب: {fields}.',
      'user_requirement_separator': '، ',
      'kyc_country': 'البلد',
      'kyc_id_type': 'نوع الهوية',
      'kyc_id_number': 'رقم الهوية',
      'kyc_document': 'المستند',
      'kyc_capture_as': 'الالتقاط كـ',
      'kyc_select_country': 'اختر البلد',
      'kyc_select_id_type': 'اختر نوع الهوية',
      'kyc_loading_id_types': 'جارٍ تحميل أنواع الهوية…',
      'kyc_select_document': 'اختر المستند',
      'kyc_loading_documents': 'جارٍ تحميل المستندات…',
      'kyc_choose_country_first': 'اختر البلد أولًا',
      'kyc_choose_id_type_first': 'اختر نوع الهوية أولًا',
      'kyc_id_number_placeholder': 'أدخل {idType}',
      'kyc_id_number_example': 'مثال: {example}',
      'kyc_id_number_invalid_example':
          'لا يطابق تنسيق {idType}، مثال: {example}',
      'kyc_id_number_invalid': 'لا يطابق تنسيق {idType}',
      'catalogue_advice_unauthorised':
          'رفض الخادم رمز هذه الجلسة. اربط جلسة جديدة، ثم حاول مرة أخرى',
      'catalogue_advice_forbidden':
          'تم رفض الوصول: قد لا تكون بيئة الإنتاج مفعّلة لهذا الشريك، أو أن هذه الشبكة غير مسموح بها',
      'catalogue_advice_offline': 'تحقق من اتصالك، ثم حاول مرة أخرى',
      'picker_country_title': 'البلد',
      'picker_country_search': 'ابحث عن بلد',
      'picker_country_no_match': 'لا يوجد بلد يطابق «{query}»',
      'picker_country_empty': 'لا توجد بلدان لهذا المنتج',
      'picker_country_empty_hint': 'جرّب منتجًا آخر',
      'picker_id_type_title': 'نوع الهوية',
      'picker_id_type_search': 'ابحث عن نوع هوية',
      'picker_id_type_no_match': 'لا يوجد نوع هوية يطابق «{query}»',
      'picker_id_type_empty': 'لا توجد أنواع هوية لـ {country}',
      'picker_document_title': 'المستند',
      'picker_document_search': 'ابحث عن مستند',
      'picker_document_no_match': 'لا يوجد مستند يطابق «{query}»',
      'picker_document_empty': 'لا توجد مستندات لـ {country}',
      'picker_choose_another_country': 'اختر بلدًا آخر',
      'picker_this_country': 'هذا البلد',
      'picker_country_loading': 'جارٍ تحميل الدول',
      'picker_country_load_failed': 'تعذّر تحميل الدول',
      'picker_id_type_loading': 'جارٍ تحميل أنواع الهوية',
      'picker_id_type_load_failed': 'تعذّر تحميل أنواع الهوية',
      'picker_document_loading': 'جارٍ تحميل المستندات',
      'picker_document_load_failed': 'تعذّر تحميل المستندات',
      'capture_as_title': 'الالتقاط كـ',
      'capture_as_match_document': 'مطابقة المستند',
      'capture_as_green_book': 'إعداد Green Book المسبق',
      'capture_as_passport': 'إعداد جواز السفر المسبق',
      'capture_as_generic_document': 'مستند عام',
      'capture_as_front_and_back': 'الوجه والظهر',
      'capture_as_front_only': 'الوجه فقط',
      'capture_as_matches': '{captureAs} · يطابق المستند',
      'capture_as_chosen': '{captureAs} · مختار',
      'capture_as_generic_summary': '{captureAs} · {orientation} · {sides}',
      'capture_as_generic_named_summary':
          '{name} · {orientation} · {sides} · مختار',
      'capture_as_match_named': 'مطابقة المستند ({captureAs})',
      'generic_document_title': 'مستند عام',
      'generic_document_display_name': 'الاسم المعروض',
      'generic_document_default_name': 'مستند',
      'generic_document_back_side': 'الوجه الخلفي',
      'generic_document_back_side_hint': 'التقط الظهر بعد الوجه',
      'generic_document_orientation': 'الاتجاه',
      'generic_document_landscape': 'أفقي',
      'generic_document_portrait': 'رأسي',
      'generic_document_aspect_ratio': 'نسبة العرض إلى الارتفاع',
      'generic_document_ratio_off': 'بدون',
      'generic_document_ratio_card': 'بطاقة 1.586',
      'generic_document_ratio_passport': 'جواز سفر 1.309',
      'generic_document_ratio_booklet': 'كتيّب 0.748',
      'verifications_title': 'عمليات التحقق',
      'verifications_select': 'تحديد',
      'verifications_empty_title': 'لا توجد عمليات تحقق بعد',
      'verifications_empty_body': 'ابدأ أحد المنتجات أعلاه وستظهر العملية هنا.',
      'verifications_filtered_empty_title': 'لا شيء في {filter}',
      'verifications_filtered_empty_body':
          'لا تزال هناك عمليات تحقق في عوامل تصفية أخرى.',
      'verifications_filter_all': 'الكل',
      'verifications_today': 'اليوم',
      'verifications_yesterday': 'أمس',
      'verifications_selected': 'المحدد: {count}',
      'verifications_tap_rows': 'انقر على الصفوف لتحديدها',
      'verifications_tap_hide': 'انقر على «إخفاء من القائمة» للتأكيد',
      'verifications_hide_from_list': 'إخفاء من القائمة',
      'verifications_hidden_one': 'تم إخفاء تحقق واحد من قائمة التطبيق',
      'verifications_hidden_many':
          'تم إخفاء {count} من عمليات التحقق من قائمة التطبيق',
      'status_clear': 'سليمة',
      'status_attention': 'تحتاج مراجعة',
      'status_blocked': 'محظورة',
      'status_processing': 'قيد المعالجة',
      'job_result_approved': 'مقبولة',
      'job_result_provisional': 'مؤقتة — تحتاج مراجعة',
      'job_result_rejected': 'مرفوضة',
      'job_result_submitted': 'أُرسلت، بانتظار النتيجة',
      'job_error_not_stored': 'لم تعد عملية التحقق محفوظة',
      'job_error_unreachable': 'تعذّر الوصول إلى الخادم',
      'job_error_unexpected': 'خطأ غير متوقع: {type}',
      'status_refresh_result': '{status} — {message}',
      'status_refresh_processing': 'لا يزال قيد المعالجة',
      'status_refresh_no_session': 'امسح رمزًا أولًا',
      'status_refresh_not_token_job': 'لم يُرسل باستخدام رمز ممسوح',
      'status_refresh_other_partner': 'أُرسل بواسطة شريك آخر',
      'status_refresh_failed': 'تعذّر التحقق من الحالة: {reason}',
      'details_title': 'تفاصيل عملية التحقق',
      'details_missing_title': 'لا توجد عملية تحقق هنا',
      'details_missing_body': 'لا شيء محفوظ لـ jobId = {jobId}',
      'details_hide': 'إخفاء عملية التحقق من قائمة التطبيق',
      'details_section': 'التفاصيل',
      'details_job_id': 'معرّف العملية',
      'details_user_id': 'معرّف المستخدم',
      'details_message': 'الرسالة',
      'details_status': 'الحالة',
      'details_copied': 'تم نسخ {label}',
      'details_copy_failed': 'تعذّر نسخ {label}',
      'profiles_title': 'الملفات الشخصية',
      'profiles_active_suffix': ' · نشط',
      'profiles_create': 'إنشاء ملف شخصي جديد',
      'profiles_create_hint': 'ستُحفظ بيانات المستخدم ضمنه',
      'profiles_no_profile': 'لا يوجد ملف شخصي بعد',
      'profiles_unnamed': 'ملف شخصي بلا اسم',
      'profiles_no_details': 'لا توجد بيانات مستخدم بعد',
      'profiles_created': 'تم إنشاء {profile}',
      'profiles_make_active': 'تفعيل',
      'profile_config_section_profile': 'الملف الشخصي',
      'profile_config_name': 'اسم الملف الشخصي',
      'profile_config_name_hint': 'يظهر في شاشة الموافقة',
      'profile_config_section_details': 'بيانات المستخدم — تُرفق بكل عملية',
      'profile_config_section_callback': 'عنوان رد الاتصال',
      'profile_config_callback_label': 'عنوان Webhook',
      'profile_config_callback_hint': 'يستخدم القيمة الافتراضية في بوابتك',
      'profile_config_delete': 'حذف الملف الشخصي',
      'profile_config_save': 'حفظ التغييرات',
      'profile_config_use': 'استخدام هذا الملف الشخصي',
      'profile_config_delete_title': 'حذف {profile}؟',
      'profile_config_delete_body':
          'ستُحذف بياناته وعنوان رد الاتصال الخاص به من هذا الجهاز.',
      'profile_switch_title': 'تبديل الملف الشخصي',
      'profile_switch_new': 'ملف شخصي جديد',
      'profile_switch_new_hint': 'تشغيل العمليات باسم شخص آخر',
      'new_profile_title': 'ملف شخصي جديد',
      'new_profile_name': 'اسم الملف الشخصي',
      'new_profile_section_details': 'بيانات المستخدم',
      'new_profile_create': 'إنشاء الملف الشخصي',
      'settings_title': 'الإعدادات',
      'settings_section_profile': 'الملف الشخصي',
      'settings_profile_configure': 'انقر للإعداد',
      'settings_profile_create': 'انقر لإنشاء ملف',
      'settings_section_capture': 'الالتقاط',
      'settings_enhanced_smart_selfie': '⁦Enhanced SmartSelfie™⁩',
      'settings_enhanced_smart_selfie_body': 'يستخدم التقاط الوجه حركات الرأس',
      'settings_enhanced_smart_selfie_mutex': 'يوقف وضع الوكيل',
      'settings_agent_mode': 'وضع الوكيل',
      'settings_agent_mode_body': 'يلتقط المشغّل الصور نيابةً عن مقدّم الطلب',
      'settings_agent_mode_mutex': 'يوقف {setting}',
      'settings_section_appearance': 'المظهر',
      'settings_theme': 'السمة',
      'settings_section_language': 'اللغة',
      'settings_language': 'اللغة',
      'settings_section_sdk_screens':
          'شاشات SDK — إظهار خطوات التدفق أو تخطيها',
      'settings_consent': 'شاشة الموافقة',
      'settings_consent_body': 'طلب الإذن قبل عمليات KYC',
      'settings_consent_bound': 'يمنح الرمز الموافقة، لذا تُتخطّى الشاشة',
      'settings_instructions': 'شاشة التعليمات',
      'settings_instructions_body': 'نصائح قبل الالتقاط',
      'settings_preview': 'شاشة المعاينة',
      'settings_preview_body': 'التأكيد أو إعادة الالتقاط بعد الالتقاط',
      'settings_section_document_capture': 'التقاط المستند',
      'settings_capture_mode': 'وضع الالتقاط',
      'settings_gallery_upload': 'الرفع من المعرض',
      'settings_gallery_upload_body': 'منتقي النظام لا يحتاج إلى إذن',
      'settings_skip_back': 'تخطّي الظهر',
      'settings_skip_back_body': 'زر تخطٍّ عند التقاط الوجه الخلفي',
      'settings_selfie_first': 'الصورة الذاتية أولًا',
      'settings_selfie_first_body': 'الصورة الذاتية قبل المستند',
      'settings_section_about': 'حول',
      'settings_documentation': 'الوثائق',
      'settings_support': 'الدعم',
      'settings_support_body': 'تواصل مع فريق Smile',
      'settings_section_legal': 'قانوني',
      'settings_terms': 'شروط الخدمة',
      'settings_privacy': 'سياسة الخصوصية',
      'settings_licenses': 'تراخيص المصادر المفتوحة',
      'settings_sign_out': 'تسجيل الخروج',
      'settings_sign_out_title': 'تسجيل الخروج؟',
      'settings_sign_out_body':
          'سيؤدي هذا إلى إنهاء جلسة الرمز وحذف كل الملفات الشخصية على هذا الجهاز.',
      'flow_invalid': 'لم يجتز مسار التحقق التحقق من الصحة',
      'capture_mode_title': 'وضع الالتقاط',
      'capture_mode_auto': 'تلقائي',
      'capture_mode_manual': 'يدوي',
      'capture_mode_auto_with_fallback': 'تلقائي مع بديل يدوي',
      'capture_mode_auto_body': 'يلتقط الصورة عند ثبات المستند',
      'capture_mode_manual_body': 'يظهر زر الالتقاط فورًا',
      'capture_mode_auto_with_fallback_body': 'يظهر زر الالتقاط بعد 10 ثوانٍ',
      'appearance_title': 'السمة',
      'appearance_system_light': 'النظام (فاتح)',
      'appearance_system_dark': 'النظام (داكن)',
      'appearance_light': 'فاتح',
      'appearance_dark': 'داكن',
      'language_title': 'اللغة',
      'language_system': 'النظام ({language})',
      'language_applies_on_relaunch':
          'يُطبَّق في المرة القادمة التي يُفتح فيها التطبيق.',
      'licenses_title': 'تراخيص المصادر المفتوحة',
      'licenses_empty_title': 'لا توجد إشعارات مضمّنة',
      'licenses_empty_body':
          'ملف licenses.json المُنشأ غير موجود في هذا الإصدار',
      'licenses_section': 'مكوّنات مفتوحة المصدر — {count}',
      'licenses_google_section': 'بموجب شروط Google الخاصة — {count}',
      'licenses_text_ships_with_component': 'يُرفق النص مع المكوّن نفسه.',
      'licenses_text_ships_with_component_at':
          'يأتي النص مع المكوّن نفسه، على {url}',
      'licenses_open': 'فتح {license}',
    },
    'he': {
      'common_cancel': 'ביטול',
      'common_continue': 'המשך',
      'common_retry': 'ניסיון חוזר',
      'common_try_again': 'נסה שוב',
      'common_done': 'סיום',
      'common_delete': 'מחיקה',
      'common_hide': 'הסתרה',
      'common_back': 'חזרה',
      'common_undo': 'ביטול פעולה',
      'common_close_named': 'סגירת {title}',
      'common_copy_named': 'העתקת {label}',
      'common_required_named': '{label} *',
      'common_search': 'חיפוש',
      'nav_products': 'מוצרים',
      'nav_verifications': 'אימותים',
      'nav_settings': 'הגדרות',
      'nav_token': 'טוקן',
      'nav_token_session': 'סשן טוקן',
      'products_title': 'Smile ID',
      'products_subtitle':
          'נסו את חבילת המוצרים שלנו, המבוססת על ערכות ה-SDK שלנו נגד הונאות',
      'products_switch_profile': 'החלפת פרופיל',
      'products_section_authentication': 'אימות זהות',
      'products_section_onboarding': 'הצטרפות',
      'product_smart_selfie_enrollment': 'רישום SmartSelfie',
      'product_smart_selfie_authentication': 'אימות SmartSelfie',
      'product_document_verification': 'אימות מסמך',
      'product_enhanced_document_verification': 'אימות מסמך מורחב',
      'product_residency_document_verification': 'אימות מסמך תושבות',
      'product_biometric_kyc': 'KYC ביומטרי',
      'product_enhanced_kyc': 'KYC מורחב',
      'product_card_registration': 'רישום',
      'product_card_auth': 'אימות',
      'product_card_document': 'מסמך',
      'product_card_enhanced_doc': 'מסמך מורחב',
      'product_card_residency_doc': 'מסמך תושבות',
      'product_card_biometric': 'ביומטרי',
      'product_card_enhanced': 'מורחב',
      'product_family_verification': 'אימות',
      'product_family_kyc': 'KYC',
      'session_active': 'סשן טוקן פעיל',
      'session_linked_to': 'מקושר לסשן {sessionId}',
      'session_ended': 'סשן הטוקן הסתיים',
      'session_relink': 'סרקו טוקן כדי לקשר מחדש',
      'session_scan': 'סריקה',
      'scan_title': 'סריקת טוקן',
      'scan_flash_on': 'הפעלת הפלאש',
      'scan_flash_off': 'כיבוי הפלאש',
      'scan_point': 'כוונו אל קוד QR של טוקן Smile',
      'scan_line_up': 'מקמו את הקוד בתוך המסגרת כדי לקשר את המכשיר לסשן אימות.',
      'scan_portal_prefix': 'קבלו טוקן v3 מ',
      'scan_portal_link': 'פורטל Smile ID',
      'scan_portal_suffix': ', תחת הגדרות האבטחה.',
      'scan_manual_entry': 'או הזינו את הטוקן ידנית',
      'scan_paste': 'הדבקה',
      'scan_link_token': 'קישור הטוקן',
      'scan_simulated': 'סריקה מדומה',
      'scan_simulate': 'הדמיית סריקה מוצלחת',
      'scan_binds_consent': 'כולל הסכמה',
      'scan_binds_details': 'כולל פרטים',
      'scan_found': 'נמצא טוקן',
      'scan_linked': 'הסשן קושר',
      'scan_not_a_token': 'זה לא טוקן',
      'scan_reading': 'קורא אותו עכשיו',
      'scan_remaining': '{handle} · נותרו {remaining}',
      'scan_clipboard_empty': 'אין בלוח טקסט להדבקה.',
      'scan_reason_session_ended':
          'סשן הטוקן הסתיים. סרקו כדי להמשיך מהמקום שבו עצרתם.',
      'scan_reason_needed': 'סרקו טוקן כדי להתחיל את האימות.',
      'scan_span_expired': 'פג תוקף',
      'scan_environment_sandbox': 'סביבת ניסוי',
      'scan_environment_production': 'סביבת ייצור',
      'token_error_segments':
          'טוקן מורכב משלושה מקטעי base64url המופרדים בנקודות, וזה לא.',
      'token_error_payload_encoding':
          'מקטע המטען של הטוקן אינו בקידוד base64url.',
      'token_error_payload_json': 'מקטע המטען של הטוקן אינו אובייקט JSON.',
      'token_error_iat': 'בטוקן אין טענת iat מספרית.',
      'token_error_exp': 'בטוקן אין טענת exp מספרית.',
      'token_error_exp_order':
          'טענת ה-exp של הטוקן אינה מאוחרת מטענת ה-iat שלו.',
      'token_error_api_url_missing':
          'בטוקן אין טענת api_url, ולכן שום דבר לא מציין לאיזו סביבה הוא הונפק.',
      'token_error_api_url_unknown':
          'ה-api_url של הטוקן מציין את {host}, שאינו סביבה של Smile ID.',
      'token_error_api_url_invalid':
          'ה-api_url של הטוקן אינו כתובת URL, ולכן אינו מציין סביבה.',
      'token_callback_set': 'הוגדר על ידי הטוקן שנסרק',
      'token_callback_default': 'חלה ברירת המחדל של השותף מהטוקן שנסרק',
      'user_details_save_to': 'שמירה ב-{profile}',
      'user_details_save_new': 'שמירה כפרופיל חדש',
      'user_details_no_profile': 'הפרטים שלכם למטה ייצרו פרופיל',
      'user_details_switch_profile': 'הקישו כדי להחליף פרופיל',
      'user_details_section': 'הפרטים שלכם',
      'user_details_profile_name': 'שם הפרופיל (אופציונלי)',
      'user_details_profile_name_hint': 'מוצג במסך ההסכמה',
      'user_details_from_token': 'סופק על ידי הטוקן',
      'user_details_edit_hint': 'הקישו על שדה כדי לערוך.',
      'user_field_first_name': 'שם פרטי',
      'user_field_last_name': 'שם משפחה',
      'user_field_email': 'אימייל',
      'user_field_phone': 'טלפון',
      'user_field_email_optional': 'אימייל (אופציונלי)',
      'user_field_phone_optional': 'טלפון (אופציונלי)',
      'user_field_first_name_placeholder': 'הוספת שם פרטי',
      'user_field_last_name_placeholder': 'הוספת שם משפחה',
      'user_field_email_placeholder': 'name@company.com',
      'user_field_phone_placeholder': '+254 700 000 000',
      'user_field_email_error': 'הזינו אימייל כמו name@company.com.',
      'user_field_phone_error':
          'הזינו את המספר עם קידומת המדינה, כמו ‎+254 700 000 000.',
      'user_requirement_first_name': 'שם פרטי',
      'user_requirement_last_name': 'שם משפחה',
      'user_requirement_contact': 'אימייל או מספר טלפון',
      'user_requirement_one': 'חובה: {field}.',
      'user_requirement_many': 'חובה: {fields}.',
      'user_requirement_separator': ', ',
      'kyc_country': 'מדינה',
      'kyc_id_type': 'סוג תעודה',
      'kyc_id_number': 'מספר תעודה',
      'kyc_document': 'מסמך',
      'kyc_capture_as': 'צילום בתור',
      'kyc_select_country': 'בחירת מדינה',
      'kyc_select_id_type': 'בחירת סוג תעודה',
      'kyc_loading_id_types': 'טוען סוגי תעודות…',
      'kyc_select_document': 'בחירת מסמך',
      'kyc_loading_documents': 'טוען מסמכים…',
      'kyc_choose_country_first': 'בחרו קודם מדינה',
      'kyc_choose_id_type_first': 'בחרו קודם סוג תעודה',
      'kyc_id_number_placeholder': 'הזינו את ה{idType} שלכם',
      'kyc_id_number_example': 'לדוגמה {example}',
      'kyc_id_number_invalid_example':
          'לא תואם לפורמט {idType}, לדוגמה {example}',
      'kyc_id_number_invalid': 'לא תואם לפורמט {idType}',
      'catalogue_advice_unauthorised':
          'השרת דחה את הטוקן של הסשן הזה. קשרו סשן חדש ונסו שוב',
      'catalogue_advice_forbidden':
          'הגישה נדחתה: ייתכן שסביבת הייצור לא הופעלה עבור השותף הזה, או שהרשת הזו אינה מורשית',
      'catalogue_advice_offline': 'בדקו את החיבור ונסו שוב',
      'picker_country_title': 'מדינה',
      'picker_country_search': 'חיפוש מדינה',
      'picker_country_no_match': 'אין מדינה שתואמת ל„{query}”',
      'picker_country_empty': 'אין מדינות למוצר הזה',
      'picker_country_empty_hint': 'נסו מוצר אחר',
      'picker_id_type_title': 'סוג תעודה',
      'picker_id_type_search': 'חיפוש סוג תעודה',
      'picker_id_type_no_match': 'אין סוג תעודה שתואם ל„{query}”',
      'picker_id_type_empty': 'אין סוגי תעודות עבור {country}',
      'picker_document_title': 'מסמך',
      'picker_document_search': 'חיפוש מסמך',
      'picker_document_no_match': 'אין מסמך שתואם ל„{query}”',
      'picker_document_empty': 'אין מסמכים עבור {country}',
      'picker_choose_another_country': 'בחרו מדינה אחרת',
      'picker_this_country': 'המדינה הזו',
      'picker_country_loading': 'טוען מדינות',
      'picker_country_load_failed': 'לא ניתן לטעון מדינות',
      'picker_id_type_loading': 'טוען סוגי תעודות',
      'picker_id_type_load_failed': 'לא ניתן לטעון סוגי תעודות',
      'picker_document_loading': 'טוען מסמכים',
      'picker_document_load_failed': 'לא ניתן לטעון מסמכים',
      'capture_as_title': 'צילום בתור',
      'capture_as_match_document': 'התאמה למסמך',
      'capture_as_green_book': 'הגדרה מוכנה ל-Green Book',
      'capture_as_passport': 'הגדרה מוכנה לדרכון',
      'capture_as_generic_document': 'מסמך כללי',
      'capture_as_front_and_back': 'חזית וגב',
      'capture_as_front_only': 'חזית בלבד',
      'capture_as_matches': '{captureAs} · תואם למסמך',
      'capture_as_chosen': '{captureAs} · נבחר',
      'capture_as_generic_summary': '{captureAs} · {orientation} · {sides}',
      'capture_as_generic_named_summary':
          '{name} · {orientation} · {sides} · נבחר',
      'capture_as_match_named': 'התאמה למסמך ({captureAs})',
      'generic_document_title': 'מסמך כללי',
      'generic_document_display_name': 'שם לתצוגה',
      'generic_document_default_name': 'מסמך',
      'generic_document_back_side': 'צד אחורי',
      'generic_document_back_side_hint': 'צלמו את הגב אחרי החזית',
      'generic_document_orientation': 'כיוון',
      'generic_document_landscape': 'לרוחב',
      'generic_document_portrait': 'לאורך',
      'generic_document_aspect_ratio': 'יחס גובה-רוחב',
      'generic_document_ratio_off': 'ללא',
      'generic_document_ratio_card': 'כרטיס 1.586',
      'generic_document_ratio_passport': 'דרכון 1.309',
      'generic_document_ratio_booklet': 'פנקס 0.748',
      'verifications_title': 'אימותים',
      'verifications_select': 'בחירה',
      'verifications_empty_title': 'עדיין אין אימותים',
      'verifications_empty_body': 'התחילו מוצר למעלה והעבודה תופיע כאן.',
      'verifications_filtered_empty_title': 'אין {filter}',
      'verifications_filtered_empty_body': 'במסננים אחרים עדיין יש אימותים.',
      'verifications_filter_all': 'הכול',
      'verifications_today': 'היום',
      'verifications_yesterday': 'אתמול',
      'verifications_selected': 'נבחרו: {count}',
      'verifications_tap_rows': 'הקישו על שורות כדי לבחור',
      'verifications_tap_hide': 'הקישו על „הסתרה מהרשימה” כדי לאשר',
      'verifications_hide_from_list': 'הסתרה מהרשימה',
      'verifications_hidden_one': 'אימות אחד הוסתר מרשימת האפליקציה',
      'verifications_hidden_many': '{count} אימותים הוסתרו מרשימת האפליקציה',
      'status_clear': 'תקין',
      'status_attention': 'דורש בדיקה',
      'status_blocked': 'חסום',
      'status_processing': 'בעיבוד',
      'job_result_approved': 'אושר',
      'job_result_provisional': 'זמני — דורש בדיקה',
      'job_result_rejected': 'נדחה',
      'job_result_submitted': 'נשלח, ממתין לתוצאה',
      'job_error_not_stored': 'האימות כבר לא שמור',
      'job_error_unreachable': 'לא ניתן להתחבר לשרת',
      'job_error_unexpected': 'שגיאה לא צפויה: {type}',
      'status_refresh_result': '{status} — {message}',
      'status_refresh_processing': 'עדיין בעיבוד',
      'status_refresh_no_session': 'סרקו קודם טוקן',
      'status_refresh_not_token_job': 'לא נשלח עם טוקן שנסרק',
      'status_refresh_other_partner': 'נשלח על ידי שותף אחר',
      'status_refresh_failed': 'לא ניתן לבדוק את הסטטוס: {reason}',
      'details_title': 'פרטי האימות',
      'details_missing_title': 'אין כאן אימות',
      'details_missing_body': 'לא נשמר דבר עבור jobId = {jobId}',
      'details_hide': 'הסתרת האימות מרשימת האפליקציה',
      'details_section': 'פרטים',
      'details_job_id': 'מזהה עבודה',
      'details_user_id': 'מזהה משתמש',
      'details_message': 'הודעה',
      'details_status': 'סטטוס',
      'details_copied': '{label} הועתק',
      'details_copy_failed': 'לא ניתן להעתיק את {label}',
      'profiles_title': 'פרופילים',
      'profiles_active_suffix': ' · פעיל',
      'profiles_create': 'יצירת פרופיל חדש',
      'profiles_create_hint': 'פרטי המשתמש יישמרו תחתיו',
      'profiles_no_profile': 'עדיין אין פרופיל',
      'profiles_unnamed': 'פרופיל ללא שם',
      'profiles_no_details': 'עדיין אין פרטי משתמש',
      'profiles_created': '{profile} נוצר',
      'profiles_make_active': 'הפיכה לפעיל',
      'profile_config_section_profile': 'פרופיל',
      'profile_config_name': 'שם הפרופיל',
      'profile_config_name_hint': 'מוצג במסך ההסכמה',
      'profile_config_section_details': 'פרטי משתמש — מצורפים לכל עבודה',
      'profile_config_section_callback': 'כתובת Callback',
      'profile_config_callback_label': 'כתובת Webhook',
      'profile_config_callback_hint': 'משתמש בברירת המחדל של הפורטל שלכם',
      'profile_config_delete': 'מחיקת הפרופיל',
      'profile_config_save': 'שמירת השינויים',
      'profile_config_use': 'שימוש בפרופיל הזה',
      'profile_config_delete_title': 'למחוק את {profile}?',
      'profile_config_delete_body':
          'הפרטים וכתובת ה-Callback שלו יוסרו מהמכשיר.',
      'profile_switch_title': 'החלפת פרופיל',
      'profile_switch_new': 'פרופיל חדש',
      'profile_switch_new_hint': 'הרצת עבודות בשם מישהו אחר',
      'new_profile_title': 'פרופיל חדש',
      'new_profile_name': 'שם הפרופיל',
      'new_profile_section_details': 'פרטי משתמש',
      'new_profile_create': 'יצירת פרופיל',
      'settings_title': 'הגדרות',
      'settings_section_profile': 'פרופיל',
      'settings_profile_configure': 'הקישו להגדרה',
      'settings_profile_create': 'הקישו כדי ליצור פרופיל',
      'settings_section_capture': 'צילום',
      'settings_enhanced_smart_selfie': '⁦Enhanced SmartSelfie™⁩',
      'settings_enhanced_smart_selfie_body': 'צילום הפנים משתמש בתנועות ראש',
      'settings_enhanced_smart_selfie_mutex': 'מכבה את מצב הסוכן',
      'settings_agent_mode': 'מצב סוכן',
      'settings_agent_mode_body': 'מפעיל מצלם עבור המבקש',
      'settings_agent_mode_mutex': 'מכבה את {setting}',
      'settings_section_appearance': 'מראה',
      'settings_theme': 'ערכת נושא',
      'settings_section_language': 'שפה',
      'settings_language': 'שפה',
      'settings_section_sdk_screens': 'מסכי SDK — הצגה או דילוג על שלבים',
      'settings_consent': 'מסך הסכמה',
      'settings_consent_body': 'בקשת הרשאה לפני בדיקות KYC',
      'settings_consent_bound': 'הטוקן מעניק הסכמה, ולכן המסך מדולג',
      'settings_instructions': 'מסך הוראות',
      'settings_instructions_body': 'טיפים לפני הצילום',
      'settings_preview': 'מסך תצוגה מקדימה',
      'settings_preview_body': 'אישור או צילום מחדש אחרי הצילום',
      'settings_section_document_capture': 'צילום מסמך',
      'settings_capture_mode': 'מצב צילום',
      'settings_gallery_upload': 'העלאה מהגלריה',
      'settings_gallery_upload_body': 'בורר המערכת לא דורש הרשאה',
      'settings_skip_back': 'דילוג על הגב',
      'settings_skip_back_body': 'כפתור דילוג בצילום הצד האחורי',
      'settings_selfie_first': 'סלפי קודם',
      'settings_selfie_first_body': 'הסלפי לפני המסמך',
      'settings_section_about': 'אודות',
      'settings_documentation': 'תיעוד',
      'settings_support': 'תמיכה',
      'settings_support_body': 'פנייה לצוות Smile',
      'settings_section_legal': 'משפטי',
      'settings_terms': 'תנאי השימוש',
      'settings_privacy': 'מדיניות הפרטיות',
      'settings_licenses': 'רישיונות קוד פתוח',
      'settings_sign_out': 'יציאה',
      'settings_sign_out_title': 'לצאת?',
      'settings_sign_out_body':
          'פעולה זו מסיימת את סשן הטוקן ומוחקת את כל הפרופילים במכשיר.',
      'flow_invalid': 'תהליך האימות לא עבר בדיקת תקינות',
      'capture_mode_title': 'מצב צילום',
      'capture_mode_auto': 'אוטומטי',
      'capture_mode_manual': 'ידני',
      'capture_mode_auto_with_fallback': 'אוטומטי עם גיבוי ידני',
      'capture_mode_auto_body': 'מצלם כשהמסמך מוחזק יציב',
      'capture_mode_manual_body': 'כפתור הצילום מופיע מיד',
      'capture_mode_auto_with_fallback_body':
          'כפתור הצילום מופיע אחרי 10 שניות',
      'appearance_title': 'ערכת נושא',
      'appearance_system_light': 'מערכת (בהירה)',
      'appearance_system_dark': 'מערכת (כהה)',
      'appearance_light': 'בהירה',
      'appearance_dark': 'כהה',
      'language_title': 'שפה',
      'language_system': 'מערכת ({language})',
      'language_applies_on_relaunch': 'יחול בפעם הבאה שהאפליקציה תיפתח.',
      'licenses_title': 'רישיונות קוד פתוח',
      'licenses_empty_title': 'לא צורפו הודעות',
      'licenses_empty_body': 'הקובץ licenses.json שנוצר חסר בגרסה זו',
      'licenses_section': 'רכיבי קוד פתוח — {count}',
      'licenses_google_section': 'בכפוף לתנאים של Google — {count}',
      'licenses_text_ships_with_component': 'הטקסט מצורף לרכיב עצמו.',
      'licenses_text_ships_with_component_at':
          'הטקסט מצורף לרכיב עצמו, בכתובת {url}',
      'licenses_open': 'פתיחת {license}',
    },
  };
}
