#!/usr/bin/env python3
"""Writes the Flutter app's notices for the assets bundled in the tree, from spec/bundled-assets.json.

Flutter's own build collects every package's licence, but not a font or icon a package bundles, so
these reach the licences screen only through this generated file.

    scripts/generate_flutter_bundled_notices.py            # rewrite the committed file
    scripts/generate_flutter_bundled_notices.py --check    # fail if it is stale
"""
from __future__ import annotations

import argparse
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(REPO, "spec", "bundled-assets.json")
TEXTS = os.path.join(REPO, "scripts", "license-texts")
OUT = os.path.join(REPO, "flutter", "sample_ui", "lib", "src", "model", "use_smileid_sample_bundled_notices.g.dart")


def render(spec_path: str = SPEC, texts_dir: str = TEXTS) -> str:
    """The Dart source: one component and its verbatim text per bundled asset."""
    with open(spec_path, encoding="utf-8") as handle:
        assets = json.load(handle)["assets"]
    entries = []
    for asset in assets:
        with open(os.path.join(texts_dir, asset["textFile"]), encoding="utf-8") as handle:
            text = handle.read().strip()
        if "'''" in text:
            raise ValueError(f"{asset['textFile']} holds ''' and cannot be a raw Dart literal")
        if "'" in asset["component"]:
            raise ValueError(f"{asset['component']} holds a quote and cannot be a single-quoted Dart literal")
        # Indented as dart format leaves it, so the committed file survives the repo's formatter.
        entries.append(f"      (\n        component: '{asset['component']}',\n        text: r'''\n{text}\n''',\n      ),\n")
    return (
        "// Generated by scripts/generate_flutter_bundled_notices.py from spec/bundled-assets.json. Do not edit.\n\n"
        "/// The assets bundled in the tree, which Flutter's own licence collection cannot see.\n"
        "const List<({String component, String text})> useSmileIDSampleBundledNotices =\n"
        "    <({String component, String text})>[\n" + "".join(entries) + "    ];\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare instead of writing")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        current = open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else ""
        if current != rendered:
            print(f"{os.path.relpath(OUT, REPO)} is stale: run scripts/generate_flutter_bundled_notices.py", file=sys.stderr)
            return 1
        return 0
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print(f"wrote {os.path.relpath(OUT, REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
