#!/usr/bin/env python3
"""Generate every platform's strings and SDK overrides from spec/l10n/; see docs/localisation.md.

Usage:
    scripts/sync_l10n.py                               # write every platform
    scripts/sync_l10n.py --platform android            # one platform (repeatable)
    scripts/sync_l10n.py --check [--platform ios]      # fail if any output is stale
"""

from __future__ import annotations

import argparse
import io
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from sync_design_tokens import dart_formatted, swift_formatted  # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(REPO, "spec", "l10n")
PLATFORMS = ("android", "ios", "flutter", "expo")
ARGUMENT = re.compile(r"\{(\w+)\}")
GENERATED = "Generated by scripts/sync_l10n.py from spec/l10n/. Do not edit."


class L10nError(Exception):
    """The source is incomplete or inconsistent, so no platform output can be trusted."""


def read_json(path: str):
    with io.open(path, encoding="utf-8") as handle:
        return json.load(handle)


def load(spec: str = SPEC) -> dict:
    """Read and validate every source file; any gap fails here, before anything is written."""
    meta = read_json(os.path.join(spec, "languages.json"))
    languages = meta["languages"]
    ids = [language["id"] for language in languages]
    base = meta["base"]
    if ids[0] != base:
        raise L10nError(f"languages.json lists {ids[0]} first, but the base language is {base}")
    app = {lang: read_json(os.path.join(spec, "app", f"{lang}.json")) for lang in ids}
    sdk = {lang: read_json(os.path.join(spec, "sdk", f"{lang}.json")) for lang in ids if lang != base}
    validate_app(app, base)
    validate_sdk(sdk)
    return {
        "base": base,
        "languages": languages,
        "integers": set(meta.get("integerArguments", [])),
        "app": app,
        "sdk": sdk,
        "sdk_arguments": {
            key: value
            for key, value in read_json(os.path.join(spec, "sdk-arguments.json")).items()
            if key != "description"
        },
    }


def arguments(value: str) -> list[str]:
    """The argument names in first-appearance order, each once."""
    seen: list[str] = []
    for name in ARGUMENT.findall(value):
        if name not in seen:
            seen.append(name)
    return seen


def validate_app(app: dict[str, dict[str, str]], base: str) -> None:
    keys = list(app[base])
    for key in keys:
        if not re.fullmatch(r"[a-z][a-z0-9_]*", key):
            raise L10nError(f"app key {key!r} is not snake_case")
    for lang, values in app.items():
        missing = [key for key in keys if key not in values]
        extra = [key for key in values if key not in app[base]]
        if missing or extra:
            raise L10nError(f"app/{lang}.json: missing {missing}, unknown {extra}")
        for key in keys:
            if set(arguments(values[key])) != set(arguments(app[base][key])):
                raise L10nError(
                    f"app/{lang}.json {key}: arguments {arguments(values[key])} "
                    f"differ from {base}'s {arguments(app[base][key])}"
                )


def validate_sdk(sdk: dict[str, dict[str, str]]) -> None:
    if not sdk:
        return
    first, *rest = sdk
    for lang in rest:
        if set(sdk[lang]) != set(sdk[first]):
            diff = sorted(set(sdk[lang]) ^ set(sdk[first]))
            raise L10nError(f"sdk/{lang}.json and sdk/{first}.json override different keys: {diff}")
    for lang, values in sdk.items():
        for key, value in values.items():
            if not key.startswith("si_"):
                raise L10nError(f"sdk/{lang}.json {key}: SDK keys start with si_")
            if set(arguments(value)) != set(arguments(sdk[first][key])):
                raise L10nError(f"sdk/{lang}.json {key}: arguments differ from sdk/{first}.json")


def camel(key: str) -> str:
    head, *tail = key.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in tail)


def positional(value: str, order: list[str], token) -> str:
    """Replace each `{name}` with the platform token for its index in `order`."""
    return ARGUMENT.sub(lambda match: token(order.index(match.group(1)) + 1, match.group(1)), value)


def sdk_value(value: str, key: str, platform: str, sdk_arguments: dict) -> str:
    tokens = sdk_arguments.get(key, {}).get(platform, {})
    return ARGUMENT.sub(lambda match: tokens.get(match.group(1), match.group(0)), value)


# Android


def android_escape(value: str, formatted: bool) -> str:
    """Escape for an Android string resource, quoting whitespace aapt would otherwise collapse."""
    text = value.replace("\\", "\\\\").replace("&", "&amp;").replace("<", "&lt;")
    text = text.replace('"', '\\"').replace("'", "\\'").replace("\n", "\\n")
    if formatted:
        text = text.replace("%", "%%")
    if text[:1] in ("@", "?"):
        text = "\\" + text
    if value != value.strip() or "  " in value:
        text = f'"{text}"'
    return text


def android_app(data: dict, lang: str) -> str:
    base = data["app"][data["base"]]
    lines = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {GENERATED} -->", "<resources>"]
    for key, value in data["app"][lang].items():
        order = arguments(base[key])
        escaped = android_escape(value, formatted=bool(order))
        text = positional(
            escaped,
            order,
            lambda index, name: f"%{index}${'d' if name in data['integers'] else 's'}",
        )
        lines.append(f'    <string name="sample_{key}">{text}</string>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def android_sdk(data: dict, lang: str) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f"<!-- {GENERATED} -->",
        '<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="ExtraTranslation">',
    ]
    for key, value in data["sdk"][lang].items():
        text = android_escape(value, formatted=False)
        lines.append(f'    <string name="{key}">{sdk_value(text, key, "android", data["sdk_arguments"])}</string>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def android_locales(data: dict) -> str:
    lines = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {GENERATED} -->"]
    lines.append('<locale-config xmlns:android="http://schemas.android.com/apk/res/android">')
    lines += [f'    <locale android:name="{language["id"]}" />' for language in data["languages"]]
    lines.append("</locale-config>")
    return "\n".join(lines) + "\n"


def kotlin_accessors(data: dict) -> str:
    base = data["app"][data["base"]]
    out = [
        f"// {GENERATED}",
        "package com.usesmileid.sampleapps.ui",
        "",
        "import androidx.compose.runtime.Composable",
        "import androidx.compose.ui.res.stringResource",
        "",
        "/** The sample's own copy, one accessor per key in `spec/l10n/app/en.json`. */",
        "object UseSmileIDSampleStrings {",
    ]
    for key in base:
        order = arguments(base[key])
        resource = f"R.string.sample_{key}"
        if not order:
            out.append(f"    val {camel(key)}: String @Composable get() = stringResource({resource})")
            continue
        params = ", ".join(f"{name}: {'Int' if name in data['integers'] else 'String'}" for name in order)
        out.append(
            f"    @Composable fun {camel(key)}({params}): String = stringResource({resource}, {', '.join(order)})"
        )
    out.append("}")
    return "\n".join(out) + "\n"


def android_outputs(data: dict) -> dict[str, str]:
    ui = "android/sample-ui/src/main"
    app = "android/app/src/main/res"
    outputs = {f"{ui}/kotlin/com/usesmileid/sampleapps/ui/UseSmileIDSampleStrings.kt": kotlin_accessors(data)}
    for language in data["languages"]:
        folder, lang = language["androidFolder"], language["id"]
        outputs[f"{ui}/res/{folder}/sample_strings.xml"] = android_app(data, lang)
        if lang != data["base"]:
            outputs[f"{app}/{folder}/sdk_strings.xml"] = android_sdk(data, lang)
    outputs[f"{app}/xml/locales_config.xml"] = android_locales(data)
    return outputs


# iOS


def strings_escape(value: str, formatted: bool) -> str:
    text = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return text.replace("%", "%%") if formatted else text


def strings_file(entries: list[tuple[str, str]]) -> str:
    lines = [f"/* {GENERATED} */"] + [f'"{key}" = "{value}";' for key, value in entries]
    return "\n".join(lines) + "\n"


def ios_app(data: dict, lang: str) -> str:
    base = data["app"][data["base"]]
    entries = []
    for key, value in data["app"][lang].items():
        order = arguments(base[key])
        text = positional(
            strings_escape(value, formatted=bool(order)),
            order,
            lambda index, name: f"%{index}${'ld' if name in data['integers'] else '@'}",
        )
        entries.append((key, text))
    return strings_file(entries)


def ios_sdk(data: dict, lang: str) -> str:
    entries = []
    for key, value in data["sdk"][lang].items():
        tokens = data["sdk_arguments"].get(key, {}).get("ios", {})
        entries.append((key, sdk_value(strings_escape(value, formatted=bool(tokens)), key, "ios", data["sdk_arguments"])))
    return strings_file(entries)


def swift_accessors(data: dict) -> str:
    base = data["app"][data["base"]]
    out = [
        f"// {GENERATED}",
        "import Foundation",
        "",
        "/// The sample's own copy, one accessor per key in `spec/l10n/app/en.json`.",
        "public enum UseSmileIDSampleStrings {",
    ]
    for key in base:
        order = arguments(base[key])
        if not order:
            out.append(f'  public static var {camel(key)}: String {{ text("{key}") }}')
            continue
        params = ", ".join(f"{name}: {'Int' if name in data['integers'] else 'String'}" for name in order)
        values = ", ".join(order)
        out.append(
            f"  public static func {camel(key)}({params}) -> String {{ "
            f'String(format: text("{key}"), {values}) }}'
        )
    out += [
        "",
        "  /// Where the strings are read from; a right-to-left golden points it at one language's folder.",
        "  nonisolated(unsafe) static var bundle: Bundle = .module",
        "",
        "  private static func text(_ key: String) -> String {",
        '    NSLocalizedString(key, bundle: bundle, comment: "")',
        "  }",
        "}",
    ]
    return "\n".join(out) + "\n"


def ios_outputs(data: dict) -> dict[str, str]:
    ui = "ios/SampleUI/Sources/SampleUI"
    outputs = {f"{ui}/UseSmileIDSampleStrings.swift": swift_formatted(swift_accessors(data))}
    for language in data["languages"]:
        lang = language["id"]
        outputs[f"{ui}/Resources/{lang}.lproj/Localizable.strings"] = ios_app(data, lang)
        if lang != data["base"]:
            outputs[f"ios/App/Sources/Localization/{lang}.lproj/Localizable.strings"] = ios_sdk(data, lang)
    return outputs


# Flutter


def dart_string(value: str) -> str:
    text = value.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$").replace("\n", "\\n")
    return f"'{text}'"


def dart_strings(data: dict) -> str:
    base = data["app"][data["base"]]
    ids = [language["id"] for language in data["languages"]]
    out = [
        f"// {GENERATED}",
        "",
        "/// The sample's own copy, one accessor per key in `spec/l10n/app/en.json`.",
        "final class UseSmileIDSampleStrings {",
        "  const UseSmileIDSampleStrings._(this._values);",
        "",
        "  /// The copy for [language], or English for a language the sample does not ship.",
        "  factory UseSmileIDSampleStrings.forLanguage(String language) =>",
        "      UseSmileIDSampleStrings._(_byLanguage[language] ?? _byLanguage['" + data["base"] + "']!);",
        "",
        "  /// The language ids the sample ships, base language first.",
        f"  static const List<String> languages = [{', '.join(dart_string(i) for i in ids)}];",
        "",
        "  final Map<String, String> _values;",
        "",
        "  String _format(String key, Map<String, Object> arguments) => _values[key]!.replaceAllMapped(",
        "        RegExp(r'\\{(\\w+)\\}'),",
        "        (match) => '${arguments[match.group(1)] ?? match.group(0)}',",
        "      );",
        "",
    ]
    for key in base:
        order = arguments(base[key])
        if not order:
            out.append(f"  String get {camel(key)} => _values['{key}']!;")
            continue
        params = ", ".join(f"required {'int' if name in data['integers'] else 'String'} {name}" for name in order)
        mapping = ", ".join(f"'{name}': {name}" for name in order)
        out.append(f"  String {camel(key)}({{{params}}}) => _format('{key}', {{{mapping}}});")
    out += ["", "  static const Map<String, Map<String, String>> _byLanguage = {"]
    for lang in ids:
        out.append(f"    '{lang}': {{")
        out += [f"      '{key}': {dart_string(value)}," for key, value in data["app"][lang].items()]
        out.append("    },")
    out += ["  };", "}"]
    return "\n".join(out) + "\n"


def flutter_outputs(data: dict) -> dict[str, str]:
    outputs = {"flutter/sample_ui/lib/src/use_smileid_sample_strings.dart": dart_formatted(dart_strings(data))}
    for lang, values in data["sdk"].items():
        arb = {"@@locale": lang}
        arb.update({key: sdk_value(value, key, "flutter", data["sdk_arguments"]) for key, value in values.items()})
        outputs[f"flutter/app/lib/l10n/intl_{lang}.arb"] = json.dumps(arb, ensure_ascii=False, indent=2) + "\n"
    return outputs


# Expo


def ts_string(value: str) -> str:
    text = value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
    return f"'{text}'"


def ts_strings(data: dict) -> str:
    base = data["app"][data["base"]]
    ids = [language["id"] for language in data["languages"]]
    out = [
        f"// {GENERATED}",
        "",
        "/** A language the sample ships. */",
        f"export type UseSmileIDSampleLanguage = {' | '.join(ts_string(i) for i in ids)};",
        "",
        "/** The language ids the sample ships, base language first. */",
        f"export const useSmileIDSampleLanguages: readonly UseSmileIDSampleLanguage[] = [{', '.join(ts_string(i) for i in ids)}];",
        "",
        "type Key =",
    ]
    out += [f"  | {ts_string(key)}" for key in base]
    out[-1] += ";"
    out += [
        "",
        "/** The sample's own copy, one accessor per key in `spec/l10n/app/en.json`. */",
        "export class UseSmileIDSampleStrings {",
        "  private constructor(private readonly values: Readonly<Record<Key, string>>) {}",
        "",
        "  /** The copy for `language`, or English for a language the sample does not ship. */",
        "  static forLanguage(language: string): UseSmileIDSampleStrings {",
        f"    return new UseSmileIDSampleStrings(byLanguage[language as UseSmileIDSampleLanguage] ?? byLanguage.{data['base']});",
        "  }",
        "",
        "  private format(key: Key, args: Record<string, string | number>): string {",
        "    return this.values[key].replace(/\\{(\\w+)\\}/g, (token, name: string) => String(args[name] ?? token));",
        "  }",
    ]
    for key in base:
        order = arguments(base[key])
        out.append("")
        if not order:
            out.append(f"  get {camel(key)}(): string {{")
            out.append(f"    return this.values.{key};")
        else:
            params = "; ".join(f"{name}: {'number' if name in data['integers'] else 'string'}" for name in order)
            out.append(f"  {camel(key)}(args: {{ {params} }}): string {{")
            out.append(f"    return this.format({ts_string(key)}, args);")
        out.append("  }")
    out += ["}", "", "const byLanguage: Record<UseSmileIDSampleLanguage, Readonly<Record<Key, string>>> = {"]
    for lang in ids:
        out.append(f"  {lang}: {{")
        out += [f"    {key}: {ts_string(value)}," for key, value in data["app"][lang].items()]
        out.append("  },")
    out.append("};")
    return "\n".join(out) + "\n"


def expo_outputs(data: dict) -> dict[str, str]:
    outputs = {"expo/sample-ui/src/use-smile-id-sample-strings.ts": ts_strings(data)}
    for lang, values in data["sdk"].items():
        mapped = {key: sdk_value(value, key, "expo", data["sdk_arguments"]) for key, value in values.items()}
        outputs[f"expo/app/src/l10n/{lang}.json"] = json.dumps(mapped, ensure_ascii=False, indent=2) + "\n"
    return outputs


EMITTERS = {"android": android_outputs, "ios": ios_outputs, "flutter": flutter_outputs, "expo": expo_outputs}


def outputs(data: dict, platforms) -> dict[str, str]:
    result: dict[str, str] = {}
    for platform in platforms:
        result.update(EMITTERS[platform](data))
    return result


def sync(platforms, check: bool, repo: str = REPO, spec: str = SPEC) -> list[str]:
    """Write or compare every output; returns the paths that were stale."""
    stale = []
    for path, content in outputs(load(spec), platforms).items():
        target = os.path.join(repo, path)
        current = None
        if os.path.exists(target):
            with io.open(target, encoding="utf-8", newline="") as handle:
                current = handle.read()
        if current == content:
            continue
        stale.append(path)
        if not check:
            os.makedirs(os.path.dirname(target), exist_ok=True)
            with io.open(target, "w", encoding="utf-8", newline="") as handle:
                handle.write(content)
    return stale


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--platform", action="append", choices=PLATFORMS, help="limit to one platform; repeatable")
    parser.add_argument("--check", action="store_true", help="fail if any output is stale")
    args = parser.parse_args(argv)
    try:
        stale = sync(args.platform or PLATFORMS, args.check)
    except L10nError as error:
        print(f"spec/l10n is inconsistent: {error}", file=sys.stderr)
        return 1
    if args.check and stale:
        print("Stale localisation output; run scripts/sync_l10n.py:\n  " + "\n  ".join(stale), file=sys.stderr)
        return 1
    print("localisation output is current" if args.check else f"wrote {len(stale)} localisation outputs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
